(function(){
'use strict';
if(window.CRMV92FollowupActive) return;
const KEY='outbounder_leads_v5';
const LEGACY_KEY='crm_v62_leads';
const STAGE_KEY='crm_v92_followup_stages';
const TPL_KEY='crm_v92_followup_templates';
const UI_KEY='crm_v92_followup_ui';
const DEFAULT_STAGES=[
  {id:'primeiro',name:'Primeiro contato',color:'#1d9e75',days:0},
  {id:'segundo',name:'Segundo contato',color:'#2563eb',days:1},
  {id:'sem-resposta',name:'Tentativa sem resposta',color:'#f59e0b',days:1},
  {id:'retorno',name:'Retorno marcado',color:'#7c3aed',days:0},
  {id:'aguardando',name:'Aguardando resposta',color:'#0ea5e9',days:2},
  {id:'proposta',name:'Proposta em acompanhamento',color:'#16a34a',days:2},
  {id:'reativacao',name:'Reativação',color:'#64748b',days:7},
  {id:'encerrado',name:'Encerrado',color:'#111827',days:0}
];
const DEFAULT_TEMPLATES=[
  {id:'nao-falei',title:'Não consegui falar',channel:'WhatsApp',body:'Oi, tudo bem? Tentei falar contigo agora há pouco sobre uma oportunidade rápida para melhorar o acompanhamento dos contatos que chegam até vocês. Posso te chamar por aqui?'},
  {id:'retorno',title:'Retorno combinado',channel:'WhatsApp',body:'Oi, combinado então. Vou te chamar no horário que combinamos para dar sequência e te mostrar o próximo passo.'},
  {id:'proposta',title:'Follow-up de proposta',channel:'WhatsApp',body:'Oi, tudo bem? Passando para saber se conseguiu olhar a proposta e se faz sentido avançarmos com uma reunião rápida para ajustar os próximos passos.'},
  {id:'reuniao',title:'Confirmação de reunião',channel:'WhatsApp',body:'Oi, tudo certo? Confirmando nossa reunião. Vou te mostrar de forma objetiva onde podemos melhorar o acompanhamento dos contatos e reduzir oportunidades perdidas.'},
  {id:'ultima',title:'Última tentativa',channel:'WhatsApp',body:'Oi, tentei contato algumas vezes e não quero ficar insistindo se agora não for prioridade. Posso deixar para retomar em outro momento?'},
  {id:'reativar',title:'Reativação',channel:'WhatsApp',body:'Oi, tudo bem? Retomando nosso contato porque a ideia que conversamos pode fazer sentido agora. Quer que eu te mostre em 10 minutos?'}
];
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function readJSON(k,fb){try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):fb}catch(e){return fb}}
function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn('CRM V92: erro ao salvar',k,e)}}
function today(){return new Date().toISOString().slice(0,10)}
function addDays(d){const x=new Date();x.setDate(x.getDate()+Number(d||0));return x.toISOString().slice(0,10)}
function nowStamp(){const d=new Date();return d.toLocaleDateString('pt-BR')+' '+d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});} 
function uid(){return 'fu_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function toast(msg){let old=$('.v92-toast'); if(old) old.remove(); const el=document.createElement('div'); el.className='v92-toast'; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),2400)}
function getLeads(){let arr=readJSON(KEY,null); if(!Array.isArray(arr)) arr=readJSON(LEGACY_KEY,[]); if(!Array.isArray(arr)) arr=[]; return arr.map(normalizeLead);}
function saveLeads(list){writeJSON(KEY,list);writeJSON(LEGACY_KEY,list);try{document.dispatchEvent(new CustomEvent('crm:datachange',{detail:{source:'followup-v92'}}));}catch(e){}}
function stages(){let s=readJSON(STAGE_KEY,null); if(!Array.isArray(s)||!s.length){s=DEFAULT_STAGES;writeJSON(STAGE_KEY,s)} return s;}
function saveStages(s){writeJSON(STAGE_KEY,s)}
function templates(){let t=readJSON(TPL_KEY,null); if(!Array.isArray(t)||!t.length){t=DEFAULT_TEMPLATES;writeJSON(TPL_KEY,t)} return t;}
function saveTemplates(t){writeJSON(TPL_KEY,t)}
function ui(){return Object.assign({tab:'fila',filter:'todos',search:'',selected:null}, readJSON(UI_KEY,{}));}
function saveUI(u){writeJSON(UI_KEY,u)}
function leadName(l){return l.nome||l.empresa||l.name||l.lead||'Lead sem nome'}
function leadId(l){if(!l.id){l.id='lead_'+leadName(l).toLowerCase().replace(/[^a-z0-9]+/g,'_')+'_'+Math.random().toString(36).slice(2,5)}return l.id}
function normalizeLead(l){l=Object.assign({},l||{});leadId(l);l.nome=leadName(l);l.telefone=l.telefone||l.phone||l.whatsapp||'';l.cidade=l.cidade||l.city||'';l.segmento=l.segmento||l.segment||'';l.origem=l.origem||l.fonte||l.source||'';l.campanha=l.campanha||l.campaign||'';l.responsavel=l.responsavel||l.owner||'Time Comercial';l.etapa=l.etapa||l.pipelineEtapa||l.stage||'Lead';l.followupEtapa=l.followupEtapa||l.followupStage||l.followupStatus||l.cadenciaEtapa||'Primeiro contato';l.proximaAcao=l.proximaAcao||l.nextAction||l.acao||'Definir próximo contato';l.followup=l.followup||l.proximaData||l.nextDate||'';l.followupHora=l.followupHora||l.proximaHora||l.nextTime||'';l.prioridade=l.prioridade||l.priority||'Média';l.historico=Array.isArray(l.historico)?l.historico:(Array.isArray(l.history)?l.history:[]);l.contatos=Number(l.contatos||l.totalContatos||countEvents(l));return l;}
function countEvents(l){const h=Array.isArray(l.historico)?l.historico:[];return h.filter(e=>/ligação|whatsapp|email|reunião|follow/i.test(String(e.tipo||e.type||e.canal||''))).length;}
function leadEvents(l){return (Array.isArray(l.historico)?l.historico:[]).slice().reverse().slice(0,8);}
function stageIdFromName(name){const st=stages().find(s=>s.name===name||s.id===name);return st?st.id:String(name||'primeiro').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
function stageName(id){const st=stages().find(s=>s.id===id||s.name===id);return st?st.name:(id||'Primeiro contato')}
function statusOf(l){if(!l.followup) return 'semacao'; const d=l.followup; if(d<today()) return 'vencido'; if(d===today()) return 'hoje'; if(/retorno/i.test(l.followupEtapa||'')) return 'retorno'; return 'futuro';}
function statusLabel(l){const s=statusOf(l);return {vencido:'Vencido',hoje:'Hoje',retorno:'Retorno',semacao:'Sem próxima ação',futuro:'Futuro'}[s]||'Aberto'}
function playbookFor(l){const st=String(l.followupEtapa||'').toLowerCase();const etapa=String(l.etapa||'').toLowerCase();if(st.includes('segundo')||st.includes('sem resposta')) return 'Segundo contato — lead sem resposta';if(st.includes('proposta')||etapa.includes('proposta')) return 'Follow-up de proposta';if(st.includes('reativ')) return 'Reativação de lead frio';if(st.includes('retorno')) return 'Retorno combinado';return 'Primeiro contato — lead vindo do Garimpo';}
function filteredLeads(){const u=ui();const q=String(u.search||'').toLowerCase();let list=getLeads().filter(l=>{const blob=[l.nome,l.telefone,l.cidade,l.segmento,l.campanha,l.followupEtapa,l.etapa,l.responsavel].join(' ').toLowerCase();if(q&&!blob.includes(q)) return false;const f=u.filter||'todos';if(f==='vencidos') return statusOf(l)==='vencido';if(f==='hoje') return statusOf(l)==='hoje';if(f==='semacao') return statusOf(l)==='semacao';if(f==='risco') return statusOf(l)==='vencido'||/sem resposta|reativ/i.test(l.followupEtapa||'');if(f==='retornos') return /retorno/i.test(l.followupEtapa||'') || statusOf(l)==='retorno';return true;});return list.sort((a,b)=>{const pri={'Alta':0,'Média':1,'Media':1,'Baixa':2}; return (statusOf(a)==='vencido'?-10:0)+(pri[a.prioridade]??1) - ((statusOf(b)==='vencido'?-10:0)+(pri[b.prioridade]??1));});}
function selectedLead(){const u=ui();const list=getLeads();return list.find(l=>l.id===u.selected)||list[0]||null}
function upsertLead(updated){const list=getLeads();const idx=list.findIndex(l=>l.id===updated.id);if(idx>=0)list[idx]=normalizeLead(updated);else list.push(normalizeLead(updated));saveLeads(list);}
function addEvent(lead,ev){lead.historico=Array.isArray(lead.historico)?lead.historico:[];lead.historico.push(Object.assign({id:uid(),data:today(),hora:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),quando:nowStamp()},ev));lead.contatos=countEvents(lead);}
function doAction(id,action){const lead=getLeads().find(l=>l.id===id); if(!lead){toast('Lead não encontrado');return;} const st=stages();
  if(action==='no-response'){addEvent(lead,{tipo:'Follow-up',canal:'Ligação/WhatsApp',resultado:'Não respondeu',nota:'Tentativa registrada pela aba Follow-up.'});lead.followupEtapa='Tentativa sem resposta';lead.followup=addDays(1);lead.followupHora='10:00';lead.proximaAcao='Tentar novo contato amanhã';}
  if(action==='answered'){addEvent(lead,{tipo:'Follow-up',canal:'Contato',resultado:'Respondeu',nota:'Lead respondeu ao contato.'});lead.followupEtapa='Aguardando resposta';lead.followup=addDays(2);lead.followupHora='14:00';lead.proximaAcao='Dar sequência ao contato';}
  if(action==='return'){addEvent(lead,{tipo:'Follow-up',canal:'Contato',resultado:'Pediu retorno',nota:'Retorno marcado.'});lead.followupEtapa='Retorno marcado';lead.followup=addDays(1);lead.followupHora='15:00';lead.proximaAcao='Retornar no horário combinado';}
  if(action==='meeting'){addEvent(lead,{tipo:'Reunião',canal:'Agenda',resultado:'Marcou reunião',nota:'Reunião marcada a partir do follow-up.'});lead.followupEtapa='Aguardando resposta';lead.etapa=lead.etapa==='Lead'?'Contato':lead.etapa;lead.followup=addDays(1);lead.followupHora='09:00';lead.proximaAcao='Preparar reunião';}
  if(action==='proposal'){addEvent(lead,{tipo:'Proposta',canal:'CRM',resultado:'Enviar proposta',nota:'Lead movido para acompanhamento de proposta.'});lead.followupEtapa='Proposta em acompanhamento';lead.etapa='Proposta';lead.followup=addDays(2);lead.followupHora='10:00';lead.proximaAcao='Acompanhar proposta enviada';}
  if(action==='reactivate'){addEvent(lead,{tipo:'Reativação',canal:'CRM',resultado:'Mover para reativação',nota:'Lead entrou na fila de reativação.'});lead.followupEtapa='Reativação';lead.followup=addDays(7);lead.followupHora='10:00';lead.proximaAcao='Retomar contato em alguns dias';}
  upsertLead(lead); const u=ui(); u.selected=lead.id; saveUI(u); render(); toast('Follow-up atualizado e conectado ao Pipeline/Ligações');}
function createFollowupFromForm(){const id=$('#v92FormLead')?.value; const lead=getLeads().find(l=>l.id===id); if(!lead){toast('Escolha um lead');return;} const etapa=$('#v92FormStage')?.value||'Primeiro contato'; const date=$('#v92FormDate')?.value||today(); const hour=$('#v92FormHour')?.value||'10:00'; const note=$('#v92FormNote')?.value||'Follow-up criado manualmente.'; lead.followupEtapa=etapa; lead.followup=date; lead.followupHora=hour; lead.proximaAcao='Executar follow-up: '+etapa; addEvent(lead,{tipo:'Follow-up',canal:'Manual',resultado:'Criado',nota:note}); upsertLead(lead); const u=ui(); u.selected=lead.id; saveUI(u); closeModal(); render(); toast('Follow-up criado');}
function updateStage(id,stage){const lead=getLeads().find(l=>l.id===id); if(!lead)return; lead.followupEtapa=stageName(stage); lead.proximaAcao='Executar etapa: '+stageName(stage); addEvent(lead,{tipo:'Follow-up',canal:'Kanban',resultado:'Etapa alterada',nota:'Movido para '+stageName(stage)}); upsertLead(lead); render();}
function kpis(){const l=getLeads();return {today:l.filter(x=>statusOf(x)==='hoje').length,over:l.filter(x=>statusOf(x)==='vencido').length,no:l.filter(x=>statusOf(x)==='semacao').length,ret:l.filter(x=>/retorno/i.test(x.followupEtapa||'')).length,all:l.length,contacts:l.reduce((a,x)=>a+countEvents(x),0)};}
function hero(){return `<div class="v92-hero"><div><div class="v92-eyebrow">V92 · Follow-up ativo</div><h2>Follow-ups e Relacionamento</h2><p>Controle contatos, retornos e próximas ações de cada lead. A etapa de Follow-up anda junto com Ligações e Pipeline, sem criar cópias separadas do lead.</p></div><div class="v92-actions"><button class="btn btn-primary" data-v92-routine>Iniciar fila de hoje</button><button class="btn" data-v92-modal="followup">Criar follow-up</button><button class="btn" data-v92-modal="stages">Configurar etapas</button><button class="btn" data-v92-filter="semacao">Ver sem próxima ação</button></div></div>`}
function kpiHTML(){const d=kpis();return `<div class="v92-kpis"><button class="v92-kpi warn" data-v92-filter="hoje"><span>Hoje</span><strong>${d.today}</strong><small>Contatos programados para hoje</small></button><button class="v92-kpi danger" data-v92-filter="vencidos"><span>Vencidos</span><strong>${d.over}</strong><small>Precisam de ação imediata</small></button><button class="v92-kpi blue" data-v92-filter="semacao"><span>Sem próxima ação</span><strong>${d.no}</strong><small>Leads soltos no CRM</small></button><button class="v92-kpi" data-v92-filter="retornos"><span>Retornos marcados</span><strong>${d.ret}</strong><small>Contatos com horário combinado</small></button></div>`}
function toolbar(){const u=ui(); const opts=[['todos','Todos'],['hoje','Hoje'],['vencidos','Vencidos'],['semacao','Sem próxima ação'],['risco','Em risco'],['retornos','Retornos']]; const tabs=[['fila','Fila'],['kanban','Kanban'],['cadencias','Cadências'],['contatos','Contatos'],['templates','Templates'],['metricas','Métricas']];return `<div class="v92-toolbar"><div class="search-wrap"><input class="v92-input" id="v92Search" placeholder="Buscar lead, cidade, campanha, etapa..." value="${esc(u.search)}"></div><select class="v92-select" id="v92Filter" style="max-width:190px">${opts.map(o=>`<option value="${o[0]}" ${u.filter===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select><div class="v92-tabs">${tabs.map(t=>`<button class="v92-tab ${u.tab===t[0]?'active':''}" data-v92-tab="${t[0]}">${t[1]}</button>`).join('')}</div></div>`}
function leadRow(l){const st=statusOf(l);return `<article class="v92-lead ${st}" data-v92-select="${esc(l.id)}"><div class="v92-avatar">${esc(leadName(l).slice(0,2).toUpperCase())}</div><div><div class="v92-title"><b>${esc(leadName(l))}</b><span class="v92-pill ${st==='vencido'?'danger':st==='hoje'?'warn':st==='retorno'?'blue':'ok'}">${esc(statusLabel(l))}</span><span class="v92-pill">${esc(l.followupEtapa)}</span></div><div class="v92-meta"><span>${esc(l.telefone||'Sem telefone')}</span><span>${esc(l.cidade||'Sem cidade')}</span><span>Pipeline: ${esc(l.etapa||'Lead')}</span><span>${countEvents(l)} contatos</span></div><div class="v92-note">${esc(l.proximaAcao||'Sem próxima ação definida')} ${l.followup?`· ${esc(l.followup)} ${esc(l.followupHora||'')}`:''}</div></div><div class="v92-lead-actions"><button class="v92-mini-btn" data-v92-action="no-response" data-id="${esc(l.id)}">Não respondeu</button><button class="v92-mini-btn" data-v92-action="answered" data-id="${esc(l.id)}">Respondeu</button><button class="v92-mini-btn" data-v92-action="return" data-id="${esc(l.id)}">Pediu retorno</button><button class="v92-mini-btn" data-v92-action="meeting" data-id="${esc(l.id)}">Marcou reunião</button></div></article>`}
function listHTML(){const list=filteredLeads();return `<div class="v92-card"><div class="v92-card-head"><div><h3>Fila de próximos contatos</h3><p>Use ações rápidas para atualizar Follow-up, histórico e Pipeline.</p></div><button class="btn btn-sm" data-v92-modal="followup">Criar follow-up</button></div><div class="v92-list">${list.length?list.map(leadRow).join(''):'<div class="v92-empty"><b>Nenhum lead encontrado</b>Crie um follow-up ou envie leads do Garimpo/Ligações para esta fila.</div>'}</div></div>`}
function kanbanHTML(){const list=getLeads();const sts=stages();return `<div class="v92-card" style="padding:16px"><div class="v92-kanban" style="--v92-cols:${Math.max(sts.length,4)}">${sts.map(s=>{const col=list.filter(l=>String(l.followupEtapa||'')===s.name||String(l.followupEtapa||'')===s.id);return `<section class="v92-col" data-v92-drop="${esc(s.id)}"><div class="v92-col-head"><b>${esc(s.name)}</b><span>${col.length}</span></div><div>${col.length?col.map(l=>`<article class="v92-kan-card" draggable="true" data-v92-drag="${esc(l.id)}" data-v92-select="${esc(l.id)}" style="border-left-color:${esc(s.color||'#1d9e75')}"><b>${esc(leadName(l))}</b><p>${esc(l.proximaAcao||'Próxima ação não definida')}</p><span class="v92-pill">${countEvents(l)} contatos</span> <span class="v92-pill ${statusOf(l)==='vencido'?'danger':''}">${esc(statusLabel(l))}</span></article>`).join(''):'<div class="v92-empty" style="padding:22px 10px">Sem leads nesta etapa</div>'}</div></section>`}).join('')}</div></div>`}
function cadencesHTML(){return `<div class="v92-card"><div class="v92-card-head"><div><h3>Cadências comerciais</h3><p>Modelo simples de sequência para manter leads com próxima ação.</p></div><button class="btn btn-sm" data-v92-modal="stages">Editar etapas</button></div><div class="v92-stages">${stages().map((s,i)=>`<div class="v92-template"><b>${i+1}. ${esc(s.name)}</b><p>Prazo padrão: ${esc(s.days)} dia(s). Cor da etapa: ${esc(s.color)}.</p></div>`).join('')}</div></div>`}
function contactsHTML(){const rows=getLeads().sort((a,b)=>countEvents(b)-countEvents(a));return `<div class="v92-card"><div class="v92-card-head"><div><h3>Contatos por lead</h3><p>Quantidade de tentativas e respostas registradas no histórico.</p></div></div><div class="v92-list">${rows.length?rows.map(l=>`<article class="v92-lead" data-v92-select="${esc(l.id)}"><div class="v92-avatar">${esc(leadName(l).slice(0,2).toUpperCase())}</div><div><div class="v92-title"><b>${esc(leadName(l))}</b><span class="v92-pill blue">${countEvents(l)} contatos</span></div><div class="v92-meta"><span>Último: ${esc(leadEvents(l)[0]?.resultado||leadEvents(l)[0]?.tipo||'Sem histórico')}</span><span>Follow-up: ${esc(l.followupEtapa)}</span><span>Pipeline: ${esc(l.etapa)}</span></div></div><div class="v92-lead-actions"><button class="v92-mini-btn" data-v92-action="return" data-id="${esc(l.id)}">Criar retorno</button></div></article>`).join(''):'<div class="v92-empty">Sem contatos registrados.</div>'}</div></div>`}
function templatesHTML(){return `<div class="v92-card"><div class="v92-card-head"><div><h3>Templates rápidos</h3><p>Copie mensagens para WhatsApp/e-mail e registre o contato no lead.</p></div></div><div class="v92-template-grid">${templates().map(t=>`<button class="v92-template" data-v92-copy-template="${esc(t.id)}"><b>${esc(t.title)}</b><p>${esc(t.channel)} · ${esc(t.body)}</p></button>`).join('')}</div></div>`}
function metricsHTML(){const d=kpis();const stagesCount=stages().map(s=>[s.name,getLeads().filter(l=>l.followupEtapa===s.name||l.followupEtapa===s.id).length]);return `<div class="v92-card"><div class="v92-card-head"><div><h3>Métricas de relacionamento</h3><p>Visão simples da execução de follow-ups.</p></div></div><div class="v92-template-grid"><div class="v92-template"><b>${d.contacts}</b><p>Contatos totais registrados no histórico dos leads.</p></div><div class="v92-template"><b>${d.over}</b><p>Follow-ups vencidos que precisam de ação.</p></div><div class="v92-template"><b>${d.no}</b><p>Leads sem próxima ação definida.</p></div><div class="v92-template"><b>${d.ret}</b><p>Retornos marcados em andamento.</p></div></div><div class="v92-stages">${stagesCount.map(([n,c])=>`<div class="v92-template"><b>${esc(n)}</b><p>${c} lead(s) nesta etapa.</p></div>`).join('')}</div></div>`}
function sideHTML(){const l=selectedLead(); if(!l)return `<aside class="v92-side"><div class="v92-card"><div class="v92-empty"><b>Nenhum lead selecionado</b>Selecione um card para ver histórico, próxima ação e playbook sugerido.</div></div></aside>`; const evs=leadEvents(l);return `<aside class="v92-side"><div class="v92-card"><div class="v92-detail"><div class="v92-detail-title"><div><h3>${esc(leadName(l))}</h3><span class="v92-pill ${statusOf(l)==='vencido'?'danger':statusOf(l)==='hoje'?'warn':'ok'}">${esc(statusLabel(l))}</span></div><button class="v92-mini-btn" data-v92-modal="followup" data-lead="${esc(l.id)}">Editar</button></div><div class="v92-detail-grid"><div class="v92-info"><span>Pipeline</span><b>${esc(l.etapa)}</b></div><div class="v92-info"><span>Follow-up</span><b>${esc(l.followupEtapa)}</b></div><div class="v92-info"><span>Contatos</span><b>${countEvents(l)}</b></div><div class="v92-info"><span>Próximo</span><b>${esc(l.followup||'Sem data')} ${esc(l.followupHora||'')}</b></div></div><div class="v92-info"><span>Playbook sugerido</span><b>${esc(playbookFor(l))}</b></div><div class="v92-info"><span>Próxima ação</span><b>${esc(l.proximaAcao||'Definir próxima ação')}</b></div><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="v92-mini-btn" data-v92-action="no-response" data-id="${esc(l.id)}">Não respondeu</button><button class="v92-mini-btn" data-v92-action="return" data-id="${esc(l.id)}">Pediu retorno</button><button class="v92-mini-btn" data-v92-action="proposal" data-id="${esc(l.id)}">Enviar proposta</button><button class="v92-mini-btn" data-view="ligacoes">Abrir Ligações</button></div></div></div><div class="v92-card"><div class="v92-card-head"><div><h3>Timeline</h3><p>Histórico conectado deste lead.</p></div></div><div class="v92-detail v92-timeline">${evs.length?evs.map(e=>`<div class="v92-event"><span class="v92-dot"></span><div><b>${esc(e.resultado||e.tipo||'Contato')}</b><p>${esc(e.quando||e.data||'')} · ${esc(e.canal||e.tipo||'CRM')}<br>${esc(e.nota||e.obs||'Sem observação')}</p></div></div>`).join(''):'<div class="v92-empty" style="padding:18px">Sem histórico ainda.</div>'}</div></div></aside>`}
function currentMain(){const tab=ui().tab;if(tab==='kanban') return kanbanHTML(); if(tab==='cadencias') return cadencesHTML(); if(tab==='contatos') return contactsHTML(); if(tab==='templates') return templatesHTML(); if(tab==='metricas') return metricsHTML(); return listHTML();}
function render(){const sec=document.getElementById('cadencias'); if(!sec)return; sec.classList.add('v92-followup-view'); sec.innerHTML=`<div class="v92-shell">${hero()}${kpiHTML()}${toolbar()}<div class="v92-layout"><main>${currentMain()}</main>${sideHTML()}</div></div>${modalHTML()}`; bind(); updateTopbar();}
function updateTopbar(){const isActive=$('#cadencias.active'); if(!isActive)return; const t=$('#topbarTitle'),s=$('#topbarSub'); if(t)t.textContent='Follow-ups e Relacionamento'; if(s)s.textContent='Contatos, retornos e próximas ações conectadas ao Pipeline e Ligações';}
function bind(){const u=ui(); $('#v92Search')?.addEventListener('input',e=>{const n=ui();n.search=e.target.value;saveUI(n);render();}); $('#v92Filter')?.addEventListener('change',e=>{const n=ui();n.filter=e.target.value;saveUI(n);render();}); $$('[data-v92-tab]').forEach(b=>b.addEventListener('click',()=>{const n=ui();n.tab=b.dataset.v92Tab;saveUI(n);render();})); $$('[data-v92-filter]').forEach(b=>b.addEventListener('click',()=>{const n=ui();n.filter=b.dataset.v92Filter||'todos';n.tab='fila';saveUI(n);render();})); $$('[data-v92-select]').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('button'))return;const n=ui();n.selected=el.dataset.v92Select;saveUI(n);render();})); $$('[data-v92-action]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();doAction(b.dataset.id||ui().selected,b.dataset.v92Action)})); $$('[data-v92-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.v92Modal,b.dataset.lead))); $('[data-v92-routine]')?.addEventListener('click',()=>{const next=filteredLeads()[0];if(!next){toast('Nenhum lead na fila');return;} const n=ui();n.selected=next.id;n.tab='fila';saveUI(n);render();toast('Fila iniciada com o próximo lead prioritário');}); $$('[data-v92-copy-template]').forEach(b=>b.addEventListener('click',()=>{const t=templates().find(x=>x.id===b.dataset.v92CopyTemplate);if(!t)return;navigator.clipboard?.writeText(t.body);toast('Template copiado')})); $$('[data-v92-drag]').forEach(el=>{el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',el.dataset.v92Drag);el.classList.add('dragging')});el.addEventListener('dragend',()=>el.classList.remove('dragging'))}); $$('[data-v92-drop]').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('dragover')});col.addEventListener('dragleave',()=>col.classList.remove('dragover'));col.addEventListener('drop',e=>{e.preventDefault();col.classList.remove('dragover');const id=e.dataTransfer.getData('text/plain');if(id)updateStage(id,col.dataset.v92Drop)})});}
function modalHTML(){return `<div class="v92-modal hidden" id="v92Modal"><div class="v92-dialog"><div class="v92-dialog-head"><h3 id="v92ModalTitle">Modal</h3><button class="v92-close" data-v92-close>×</button></div><div id="v92ModalBody"></div></div></div>`}
function openModal(type,leadId){const m=$('#v92Modal'),title=$('#v92ModalTitle'),body=$('#v92ModalBody'); if(!m||!body)return; m.classList.remove('hidden'); if(type==='stages'){title.textContent='Configurar etapas de Follow-up'; body.innerHTML=stageEditorHTML(); bindModal(); return;} title.textContent='Criar / editar follow-up'; body.innerHTML=followupFormHTML(leadId||ui().selected); bindModal();}
function closeModal(){const m=$('#v92Modal'); if(m)m.classList.add('hidden');}
function bindModal(){ $$('[data-v92-close]').forEach(b=>b.addEventListener('click',closeModal)); $('#v92SaveFollowup')?.addEventListener('click',createFollowupFromForm); $('#v92SaveStages')?.addEventListener('click',saveStageEditor); $('#v92AddStage')?.addEventListener('click',()=>{const box=$('#v92StageEditor');if(box)box.insertAdjacentHTML('beforeend',stageRowHTML({id:'nova-'+Date.now(),name:'Nova etapa',color:'#1d9e75',days:1}))}); $$('[data-v92-remove-stage]').forEach(b=>b.addEventListener('click',()=>b.closest('.v92-stage-row')?.remove()));}
function followupFormHTML(selected){const leads=getLeads();const sts=stages();const l=leads.find(x=>x.id===selected)||leads[0];return `<div class="v92-form"><div class="v92-form-row"><div><div class="v92-label">Lead</div><select class="v92-select" id="v92FormLead">${leads.map(x=>`<option value="${esc(x.id)}" ${l&&x.id===l.id?'selected':''}>${esc(leadName(x))}</option>`).join('')}</select></div><div><div class="v92-label">Etapa de Follow-up</div><select class="v92-select" id="v92FormStage">${sts.map(s=>`<option value="${esc(s.name)}" ${l&&l.followupEtapa===s.name?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div></div><div class="v92-form-row"><div><div class="v92-label">Data</div><input class="v92-input" id="v92FormDate" type="date" value="${esc(l?.followup||today())}"></div><div><div class="v92-label">Horário</div><input class="v92-input" id="v92FormHour" type="time" value="${esc(l?.followupHora||'10:00')}"></div></div><div class="v92-form-row full"><div><div class="v92-label">Observação</div><textarea class="v92-textarea" id="v92FormNote" placeholder="Ex: pediu retorno, enviar proposta, tentar WhatsApp...">${esc(l?.proximaAcao||'')}</textarea></div></div><div style="display:flex;justify-content:flex-end;gap:8px"><button class="btn" data-v92-close>Cancelar</button><button class="btn btn-primary" id="v92SaveFollowup">Salvar e criar próxima ação</button></div></div>`}
function stageRowHTML(s){return `<div class="v92-stage-row"><input class="v92-input" data-stage-name value="${esc(s.name)}"><input class="v92-input" data-stage-color value="${esc(s.color||'#1d9e75')}" placeholder="#1d9e75"><button class="v92-mini-btn" type="button" data-v92-remove-stage>Remover</button><input class="v92-input" data-stage-days type="number" min="0" value="${esc(s.days??1)}" title="Prazo padrão em dias"></div>`}
function stageEditorHTML(){return `<div class="v92-form"><div class="v92-stages" id="v92StageEditor">${stages().map(stageRowHTML).join('')}</div><div style="display:flex;justify-content:space-between;gap:8px"><button class="btn" id="v92AddStage" type="button">Adicionar etapa</button><div><button class="btn" data-v92-close>Cancelar</button> <button class="btn btn-primary" id="v92SaveStages" type="button">Salvar etapas</button></div></div></div>`}
function saveStageEditor(){const rows=$$('.v92-stage-row');const s=rows.map((r,i)=>({id:stageIdFromName($('[data-stage-name]',r)?.value||('etapa-'+i)),name:$('[data-stage-name]',r)?.value||('Etapa '+(i+1)),color:$('[data-stage-color]',r)?.value||'#1d9e75',days:Number($('[data-stage-days]',r)?.value||1)})).filter(x=>x.name.trim()); if(!s.length){toast('Mantenha pelo menos uma etapa');return;} saveStages(s); closeModal(); render(); toast('Etapas salvas');}
// exposição e compatibilidade com módulos antigos
window.CRMV92FollowupActive={render,setTab:function(tab){const n=ui();n.tab=tab||'fila';saveUI(n);render();},action:doAction};
window.CRMV63Followups={render,setTab:function(tab){const n=ui();n.tab=tab||'fila';saveUI(n);render();}};
// navegação segura: não cria página nova, apenas renderiza a seção oficial.
document.addEventListener('click',function(e){const btn=e.target.closest('[data-view="cadencias"],[data-v69-go="cadencias"],[data-v68-go="cadencias"],[data-ux-go="cadencias"]'); if(btn){setTimeout(render,40);setTimeout(render,180);}},true);
document.addEventListener('crm:datachange',function(){if(document.getElementById('cadencias')?.classList.contains('active')) render();});
document.addEventListener('DOMContentLoaded',function(){if(document.getElementById('cadencias')?.classList.contains('active')) render();});
setTimeout(function(){if(document.getElementById('cadencias')?.classList.contains('active')) render();},300);
})();
