(function(){
 if(window.CRMV953RemindersCenter) return;
 const D=document;
 const $=(s,r=D)=>r.querySelector(s);
 const $$=(s,r=D)=>Array.from(r.querySelectorAll(s));
 const VERSION='V95.3';
 const LEAD_KEYS=['outbounder_leads_v5','crm_leads','leads','realtalent_leads','crm_v94_leads'];
 const RULE_KEY='crm_v952_automation_rules';
 const HIST_KEY='crm_v952_automation_history';
 const NOTIF_KEY='crm_v952_notifications';
 const REM_KEY='crm_v953_reminders';
 const REM_SETTINGS_KEY='crm_v953_reminder_settings';
 const CAT=['overview','recipes','rules','engine','reminders','history','settings'];
 let activeTab='overview';
 let reminderFilter='today';
 let recipeSearch='';
 let editReminderId=null;
 const triggerLabels={
   manual_run:'Manual',lead_created:'Lead criado',garimpo_saved:'Lead salvo do Garimpo',call_no_answer:'Ligação: não atendeu',call_answered:'Ligação: atendeu',call_return_requested:'Pediu retorno',followup_overdue:'Follow-up vencido',lead_without_next_action:'Lead sem próxima ação',lead_stuck:'Lead parado',pipeline_changed_to_proposal:'Pipeline: proposta',pipeline_closed:'Pipeline: fechado',pipeline_lost:'Pipeline: perdido'
 };
 const actionLabels={
   create_call_today:'Criar ligação para hoje',create_followup_tomorrow:'Criar follow-up para amanhã',set_followup:'Mover etapa de Follow-up',move_pipeline:'Mover etapa do Pipeline',add_tag:'Aplicar tag',set_priority:'Atualizar prioridade',suggest_playbook:'Sugerir Playbook',create_agenda_task:'Criar tarefa na Agenda',mark_risk:'Marcar lead em risco',require_loss_reason:'Exigir motivo da perda',close_followup:'Encerrar Follow-up',create_notification:'Criar notificação interna',add_history:'Registrar no histórico'
 };
 const fieldLabels={origin:'Origem',city:'Cidade',segment:'Segmento',priority:'Prioridade',pipeline:'Pipeline',followup:'Follow-up',attempts:'Tentativas',hasPhone:'Tem telefone',nextActionEmpty:'Sem próxima ação'};
 const REM_TYPES={call:'Ligação',whatsapp:'WhatsApp',followup:'Follow-up',meeting:'Reunião',task:'Tarefa',review:'Revisão',proposal:'Proposta'};
 const REM_ICONS={call:'☎️',whatsapp:'💬',followup:'↪️',meeting:'📅',task:'✓',review:'🔎',proposal:'📄'};
 const RECIPES=[
   {id:'rcp-garimpo',cat:'Captar',title:'Lead novo do Garimpo',desc:'Cria primeira ligação, aplica tag e coloca em primeiro contato.',trigger:'garimpo_saved',conditions:[{field:'origin',op:'contains',value:'Garimpo'},{field:'hasPhone',op:'is_true',value:''}],actions:[{type:'create_call_today',value:''},{type:'set_followup',value:'Primeiro contato'},{type:'add_tag',value:'Garimpo'}]},
   {id:'rcp-nao-atendeu',cat:'Contatar',title:'Não atendeu → retorno amanhã',desc:'Quando a ligação der não atendida, soma histórico, cria novo retorno e move para Sem resposta.',trigger:'call_no_answer',conditions:[{field:'attempts',op:'greater_than',value:'0'}],actions:[{type:'set_followup',value:'Sem resposta'},{type:'create_followup_tomorrow',value:'Tentar novamente'},{type:'create_notification',value:'Retorno criado após não atendimento'}]},
   {id:'rcp-proposta',cat:'Avançar',title:'Proposta enviada → follow-up em 2 dias',desc:'Ao mover para proposta, agenda acompanhamento e sugere script de proposta.',trigger:'pipeline_changed_to_proposal',conditions:[{field:'pipeline',op:'contains',value:'Proposta'}],actions:[{type:'create_agenda_task',value:'Follow-up de proposta'},{type:'suggest_playbook',value:'Follow-up de proposta'},{type:'add_tag',value:'Proposta aberta'}]},
   {id:'rcp-sem-acao',cat:'Recuperar',title:'Lead sem próxima ação',desc:'Encontra leads soltos, cria lembrete e marca como em risco.',trigger:'lead_without_next_action',conditions:[{field:'nextActionEmpty',op:'is_true',value:''}],actions:[{type:'mark_risk',value:'Sem próxima ação'},{type:'create_followup_tomorrow',value:'Definir próximo passo'},{type:'create_notification',value:'Lead estava sem próxima ação'}]},
   {id:'rcp-tentativas',cat:'Recuperar',title:'3 tentativas sem resposta',desc:'Move para reativação e sugere uma última tentativa.',trigger:'lead_stuck',conditions:[{field:'attempts',op:'greater_than',value:'2'},{field:'followup',op:'contains',value:'Sem resposta'}],actions:[{type:'set_followup',value:'Reativação'},{type:'set_priority',value:'Média'},{type:'suggest_playbook',value:'Última tentativa'}]},
   {id:'rcp-lembrete-proposta',cat:'Lembrar',title:'Lembrar proposta parada',desc:'Cria lembrete quando proposta fica sem retorno.',trigger:'pipeline_changed_to_proposal',conditions:[{field:'pipeline',op:'contains',value:'Proposta'}],actions:[{type:'create_notification',value:'Revisar proposta enviada'},{type:'create_agenda_task',value:'Revisar proposta'}]},
   {id:'rcp-fechado',cat:'Medir',title:'Fechado → pós-venda',desc:'Registra conversão, encerra follow-up comercial e cria tarefa de pós-venda.',trigger:'pipeline_closed',conditions:[{field:'pipeline',op:'contains',value:'Fechado'}],actions:[{type:'close_followup',value:'Pós-venda'},{type:'create_agenda_task',value:'Pós-venda'},{type:'create_notification',value:'Novo cliente fechado'}]}
 ];
 function uid(p){return (p||'id')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
 function readJSON(k,f){try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch(e){return f}}
 function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
 function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function today(){return new Date().toISOString().slice(0,10)}
 function nowISO(){return new Date().toISOString()}
 function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
 function addDays(n){const d=new Date();d.setDate(d.getDate()+Number(n||0));return d.toISOString().slice(0,10)}
 function nowMinutes(){const d=new Date();return d.getHours()*60+d.getMinutes()}
 function formatDate(d){if(!d)return '';try{return new Date(d).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'2-digit'})}catch(e){return String(d)}}
 function formatDateTime(date,time){if(!date)return 'Sem data';const iso=date+'T'+(time||'09:00');try{return new Date(iso).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(e){return date+' '+(time||'')}}
 function isOverdue(r){if(r.status==='done')return false;const d=String(r.dueDate||'');if(!d)return false;if(d<today())return true;if(d===today()){const parts=String(r.dueTime||'23:59').split(':');return Number(parts[0]||0)*60+Number(parts[1]||0)<nowMinutes()}return false}
 function isToday(r){return r.status!=='done'&&String(r.dueDate||'')===today()}
 function isUpcoming(r){return r.status!=='done'&&String(r.dueDate||'')>today()}
 function isSoon(r){if(!isToday(r))return false;const parts=String(r.dueTime||'23:59').split(':');const m=Number(parts[0]||0)*60+Number(parts[1]||0);const n=nowMinutes();return m>=n&&m<=n+20}
 function getSettings(){return Object.assign({defaultReminderTime:'09:00',summaryOnOpen:true,browserNotifications:false,toastBeforeMinutes:15},readJSON(REM_SETTINGS_KEY,{}))}
 function saveSettings(s){writeJSON(REM_SETTINGS_KEY,Object.assign(getSettings(),s||{}))}
 function normalizeLead(l,i){l=Object.assign({},l||{});l.id=l.id||l.leadId||uid('lead');l.empresa=l.empresa||l.nome||l.name||('Lead '+(i+1));l.nome=l.nome||l.empresa;l.telefone=l.telefone||l.phone||'';l.cidade=l.cidade||'';l.segmento=l.segmento||'';l.origem=l.origem||l.origin||'';l.pipeline=l.pipeline||l.etapa||'Lead';l.followup=l.followup||l.followupEtapa||l.statusFollowup||'Primeiro contato';l.proximaData=l.proximaData||l.nextDate||l.followupData||'';l.proximaHora=l.proximaHora||l.nextTime||'10:00';l.contatos=Number(l.contatos||l.tentativas||0);l.prioridade=l.prioridade||'Média';l.tags=Array.isArray(l.tags)?l.tags:(l.tag?[l.tag]:[]);return l}
 function findLeadKey(){for(const k of LEAD_KEYS){const v=readJSON(k,null);if(Array.isArray(v))return k}return LEAD_KEYS[0]}
 function getLeads(){let arr=[];try{if(window.CRMV94Official&&typeof window.CRMV94Official.getLeads==='function')arr=window.CRMV94Official.getLeads()}catch(e){}if(!Array.isArray(arr)||!arr.length)arr=readJSON(findLeadKey(),[]);arr=Array.isArray(arr)?arr.map(normalizeLead):[];if(!arr.length){arr=[normalizeLead({empresa:'Barbearia Alfa',telefone:'51999990001',cidade:'Porto Alegre',segmento:'Barbearia',origem:'Garimpo',pipeline:'Lead',followup:'Primeiro contato',proximaData:today(),proximaHora:'10:00',prioridade:'Alta'},0),normalizeLead({empresa:'Clínica Bella',telefone:'53999990002',cidade:'Pelotas',segmento:'Estética',origem:'Garimpo',pipeline:'Contato',followup:'Retorno marcado',proximaData:today(),proximaHora:'15:00',contatos:2,prioridade:'Alta'},1),normalizeLead({empresa:'Studio Prime',telefone:'51988880003',cidade:'Canoas',segmento:'Salão',origem:'Indicação',pipeline:'Proposta',followup:'Aguardando resposta',proximaData:addDays(1),proximaHora:'11:00',contatos:4},2)];writeJSON(findLeadKey(),arr)}return arr}
 function getLead(id){return getLeads().find(l=>l.id===id)||null}
 function getRules(){try{if(window.CRMV952RuleEngine&&typeof window.CRMV952RuleEngine.getRules==='function')return window.CRMV952RuleEngine.getRules()}catch(e){}return readJSON(RULE_KEY,[])}
 function saveRules(rules){try{if(window.CRMV952RuleEngine&&typeof window.CRMV952RuleEngine.saveRules==='function')return window.CRMV952RuleEngine.saveRules(rules)}catch(e){}writeJSON(RULE_KEY,rules)}
 function getHistory(){return readJSON(HIST_KEY,[])}
 function addHistory(h){const arr=getHistory();arr.unshift(Object.assign({id:uid('hist'),at:nowISO(),version:VERSION},h||{}));writeJSON(HIST_KEY,arr.slice(0,200))}
 function getNotifs(){return readJSON(NOTIF_KEY,[])}
 function saveNotifs(n){writeJSON(NOTIF_KEY,(n||[]).slice(0,120))}
 function addNotif(title,body,leadId){const n=getNotifs();n.unshift({id:uid('notif'),title,body,leadId,createdAt:nowISO(),read:false,source:'Lembretes V95.3'});saveNotifs(n);toast(title,body)}
 function getReminders(){let arr=readJSON(REM_KEY,null);if(!Array.isArray(arr)){arr=seedReminders();saveReminders(arr)}return arr.map(normalizeReminder)}
 function saveReminders(arr){writeJSON(REM_KEY,(arr||[]).map(normalizeReminder))}
 function normalizeReminder(r){r=Object.assign({},r||{});r.id=r.id||uid('rem');r.title=r.title||'Lembrete';r.type=r.type||'followup';r.leadId=r.leadId||'';r.dueDate=r.dueDate||today();r.dueTime=r.dueTime||getSettings().defaultReminderTime;r.priority=r.priority||'Média';r.status=r.status||'active';r.recurrence=r.recurrence||'none';r.note=r.note||'';r.channel=r.channel||r.type;return r}
 function seedReminders(){const s=getSettings();return getLeads().slice(0,6).map((l,i)=>normalizeReminder({title:(i%2?'Enviar WhatsApp para ':'Ligar para ')+l.empresa,type:i%2?'whatsapp':'call',leadId:l.id,dueDate:l.proximaData||today(),dueTime:l.proximaHora||s.defaultReminderTime,priority:l.prioridade||'Média',note:'Criado a partir da próxima ação do lead.'}))}
 function stats(){const rules=getRules();const rem=getReminders();const hist=getHistory();const n=getNotifs();return {rulesActive:rules.filter(r=>r.active!==false).length,rulesPaused:rules.filter(r=>r.active===false).length,remToday:rem.filter(isToday).length,remOverdue:rem.filter(isOverdue).length,remSoon:rem.filter(isSoon).length,remDone:rem.filter(r=>r.status==='done').length,notifs:n.filter(x=>!x.read).length,executedToday:hist.filter(h=>String(h.at||'').slice(0,10)===today()).length}}
 function toast(title,body){let old=$('.v953-toast');if(old)old.remove();const el=D.createElement('div');el.className='v953-toast';el.innerHTML=esc(title||'Pronto')+(body?'<small>'+esc(body)+'</small>':'');D.body.appendChild(el);setTimeout(()=>el.remove(),3600)}
 function shell(content){const st=stats();return `<div class="v953-wrap"><section class="v953-hero"><div><div class="v953-eyebrow">RealTalent CRM · V95.3</div><h1 class="v953-title">Automações e Lembretes</h1><p class="v953-sub">Receitas prontas, motor de regras e uma central para o CRM lembrar o que precisa ser feito hoje, o que venceu e o que está próximo.</p><div class="v953-hero-actions"><button class="v953-btn ghost" data-v953-tab="recipes">Usar receita pronta</button><button class="v953-btn ghost" data-v953-tab="reminders" data-new-reminder> Criar lembrete</button><button class="v953-btn ghost" data-run-system>Rodar verificações</button></div></div><aside class="v953-pulse-card"><div class="v953-pulse-row"><span>Próximos 20 min</span><b>${st.remSoon}</b></div><div class="v953-pulse-row"><span>Lembretes hoje</span><b>${st.remToday}</b></div><div class="v953-pulse-row"><span>Vencidos</span><b>${st.remOverdue}</b></div><div class="v953-pulse-row"><span>Notificações não lidas</span><b>${st.notifs}</b></div></aside></section><section class="v953-stats"><div class="v953-stat"><strong>${st.rulesActive}</strong><span>Automações ativas</span></div><div class="v953-stat"><strong>${st.remToday}</strong><span>Lembretes hoje</span></div><div class="v953-stat"><strong>${st.remOverdue}</strong><span>Vencidos</span></div><div class="v953-stat"><strong>${st.remSoon}</strong><span>Próximos 20 min</span></div><div class="v953-stat"><strong>${st.executedToday}</strong><span>Eventos hoje</span></div></section><nav class="v953-tabs">${tabButton('overview','Visão geral')}${tabButton('recipes','Receitas prontas')}${tabButton('rules','Minhas automações')}${tabButton('engine','Motor')}${tabButton('reminders','Lembretes')}${tabButton('history','Histórico')}${tabButton('settings','Configurações')}</nav><main>${content}</main></div>`}
 function tabButton(id,label){return `<button class="v953-tab ${activeTab===id?'active':''}" data-v953-tab="${id}">${label}</button>`}
 function render(){const el=$('#automacoes');if(!el)return;D.body.classList.add('v953-automations-ready');if(!CAT.includes(activeTab))activeTab='overview';let view='';if(activeTab==='overview')view=overviewView();if(activeTab==='recipes')view=recipesView();if(activeTab==='rules')view=rulesView();if(activeTab==='engine')view=engineView();if(activeTab==='reminders')view=remindersView();if(activeTab==='history')view=historyView();if(activeTab==='settings')view=settingsView();el.innerHTML=shell(view);bindRoot(el);checkDueReminders(false)}
 function overviewView(){const rem=getReminders();const due=rem.filter(r=>isOverdue(r)||isToday(r)).slice(0,6);const recipes=RECIPES.slice(0,3);return `<section class="v953-split"><div class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Painel de hoje</h2><p class="v953-muted">O que precisa de atenção agora.</p></div><button class="v953-btn small primary" data-v953-tab="reminders">Abrir lembretes</button></div><div class="v953-reminder-list">${due.length?due.map(reminderCard).join(''):'<div class="v953-empty">Nenhum lembrete vencido ou para hoje.</div>'}</div></div><div class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Receitas recomendadas</h2><p class="v953-muted">Atalhos estilo Trello/Butler para automatizar sem montar regra do zero.</p></div><button class="v953-btn small" data-v953-tab="recipes">Ver todas</button></div><div class="v953-grid">${recipes.map(recipeCard).join('')}</div></div></section><section class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Notificações internas</h2><p class="v953-muted">Alertas criados pelas automações e lembretes.</p></div><button class="v953-btn small" data-clear-read>Marcar todas como lidas</button></div>${notificationsList(5)}</section>`}
 function recipesView(){let list=RECIPES.filter(r=>!recipeSearch||[r.title,r.desc,r.cat].join(' ').toLowerCase().includes(recipeSearch.toLowerCase()));const cats=['Todos','Captar','Contatar','Avançar','Recuperar','Lembrar','Medir'];return `<section class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Receitas prontas</h2><p class="v953-muted">Escolha um modelo pronto, ative e depois edite se quiser.</p></div><input class="v953-field v953-search" data-search-recipes placeholder="Buscar receita" value="${esc(recipeSearch)}"></div><div class="v953-tagline">${cats.map(c=>`<button class="v953-btn small ${c==='Todos'?'dark':''}" data-recipe-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="v953-divider"></div><div class="v953-grid cols-3">${list.map(recipeCard).join('')}</div></section>`}
 function recipeCard(r){return `<article class="v953-card v953-template"><div class="v953-card-top"><div><div class="v953-card-title">${esc(r.title)}</div><p class="v953-muted">${esc(r.desc)}</p></div><span class="v953-pill ok">${esc(r.cat)}</span></div><div class="v953-flow"><div class="v953-flow-line"><b>Quando</b><span>${esc(triggerLabels[r.trigger]||r.trigger)}</span></div><div class="v953-flow-line"><b>Condições</b><span>${esc((r.conditions||[]).map(c=>(fieldLabels[c.field]||c.field)+' '+c.op+' '+(c.value||'')).join(' · ')||'Sem condição')}</span></div><div class="v953-flow-line"><b>Ações</b><span>${esc((r.actions||[]).map(a=>actionLabels[a.type]||a.type).join(' · '))}</span></div></div><div class="v953-actions"><button class="v953-btn primary small" data-activate-recipe="${esc(r.id)}">Ativar</button><button class="v953-btn small" data-copy-recipe="${esc(r.id)}">Editar cópia</button><button class="v953-btn small" data-test-recipe="${esc(r.id)}">Testar</button></div></article>`}
 function rulesView(){const rules=getRules();return `<section class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Minhas automações</h2><p class="v953-muted">Regras ativas, pausadas e criadas a partir de receitas.</p></div><button class="v953-btn primary" data-v953-tab="recipes">Adicionar por receita</button></div><div class="v953-grid cols-2">${rules.length?rules.map(ruleCard).join(''):'<div class="v953-empty">Nenhuma automação criada ainda.</div>'}</div></section>`}
 function ruleCard(r){return `<article class="v953-card"><div class="v953-card-top"><div><div class="v953-card-title">${esc(r.name||'Regra sem nome')}</div><p class="v953-muted">${esc(r.desc||r.description||describeRule(r))}</p></div><span class="v953-pill ${r.active===false?'gray':'ok'}">${r.active===false?'Pausada':'Ativa'}</span></div><div class="v953-flow"><div class="v953-flow-line"><b>Gatilho</b><span>${esc(triggerLabels[r.trigger]||r.trigger)}</span></div><div class="v953-flow-line"><b>Ações</b><span>${esc((r.actions||[]).map(a=>actionLabels[a.type]||a.type).join(' · ')||'Nenhuma')}</span></div></div><div class="v953-actions"><button class="v953-btn small" data-toggle-rule="${esc(r.id)}">${r.active===false?'Ativar':'Pausar'}</button><button class="v953-btn small" data-test-rule="${esc(r.id)}">Testar</button><button class="v953-btn small primary" data-run-rule="${esc(r.id)}">Executar agora</button><button class="v953-btn small danger" data-delete-rule="${esc(r.id)}">Excluir</button></div></article>`}
 function describeRule(r){return `Quando ${triggerLabels[r.trigger]||r.trigger}, o CRM executa ${(r.actions||[]).map(a=>actionLabels[a.type]||a.type).join(', ')||'ações configuradas'}.`}
 function engineView(){const q=readJSON('crm_v952_event_queue',[]).slice(0,8);return `<section class="v953-split"><div class="v953-panel"><h2 class="v953-title-sm">Motor de regras interno</h2><p class="v953-muted">A V95.3 usa o motor V95.2 como base. Ele processa eventos, confere condições, atualiza leads e grava histórico.</p><div class="v953-grid"><div class="v953-card"><b>Fluxo oficial</b><p class="v953-muted">Evento → Gatilho → Condições → Ações → Lead atualizado → Histórico</p></div><button class="v953-btn primary" data-run-system>Rodar verificações agora</button><button class="v953-btn" data-undo-last>Desfazer última execução</button></div><div class="v953-divider"></div><div class="v953-form-grid"><select class="v953-select" data-event-select>${Object.keys(triggerLabels).map(k=>`<option value="${k}">${triggerLabels[k]}</option>`).join('')}</select><button class="v953-btn" data-simulate-event>Simular evento</button></div></div><div class="v953-panel"><h2 class="v953-title-sm">Eventos recentes</h2><div class="v953-grid">${q.length?q.map(e=>`<div class="v953-log"><div class="v953-log-time">${esc(formatDate(e.at))}</div><div class="v953-log-main"><b>${esc(triggerLabels[e.eventType]||e.eventType)}</b><span>Evento capturado pelo motor interno.</span></div><span class="v953-pill ok">fila</span></div>`).join(''):'<div class="v953-empty">Nenhum evento recente.</div>'}</div></div></section>`}
 function remindersView(){const counts=reminderCounts();const reminders=filteredReminders();return `<section class="v953-reminder-layout"><aside class="v953-panel v953-reminder-nav"><button class="v953-reminder-filter ${reminderFilter==='today'?'active':''}" data-rem-filter="today">Hoje <b>${counts.today}</b></button><button class="v953-reminder-filter ${reminderFilter==='overdue'?'active':''}" data-rem-filter="overdue">Vencidos <b>${counts.overdue}</b></button><button class="v953-reminder-filter ${reminderFilter==='upcoming'?'active':''}" data-rem-filter="upcoming">Próximos <b>${counts.upcoming}</b></button><button class="v953-reminder-filter ${reminderFilter==='recurring'?'active':''}" data-rem-filter="recurring">Repetitivos <b>${counts.recurring}</b></button><button class="v953-reminder-filter ${reminderFilter==='done'?'active':''}" data-rem-filter="done">Concluídos <b>${counts.done}</b></button><button class="v953-btn primary" data-new-reminder>Criar lembrete</button><button class="v953-btn" data-sync-reminders>Gerar pelos leads</button></aside><main class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Central de lembretes</h2><p class="v953-muted">Lembretes vinculados a leads, ações e horários.</p></div><button class="v953-btn soft" data-check-reminders>Verificar lembretes agora</button></div>${reminderForm()}<div class="v953-reminder-list">${reminders.length?reminders.map(reminderCard).join(''):'<div class="v953-empty">Nenhum lembrete nesta categoria.</div>'}</div></main></section>`}
 function reminderCounts(){const r=getReminders();return {today:r.filter(isToday).length,overdue:r.filter(isOverdue).length,upcoming:r.filter(isUpcoming).length,recurring:r.filter(x=>x.status!=='done'&&x.recurrence!=='none').length,done:r.filter(x=>x.status==='done').length}}
 function filteredReminders(){let r=getReminders();if(reminderFilter==='today')r=r.filter(isToday);if(reminderFilter==='overdue')r=r.filter(isOverdue);if(reminderFilter==='upcoming')r=r.filter(isUpcoming);if(reminderFilter==='recurring')r=r.filter(x=>x.status!=='done'&&x.recurrence!=='none');if(reminderFilter==='done')r=r.filter(x=>x.status==='done');return r.sort((a,b)=>(a.dueDate+a.dueTime).localeCompare(b.dueDate+b.dueTime))}
 function reminderForm(){const leads=getLeads();const r=editReminderId?getReminders().find(x=>x.id===editReminderId):null;if(!r)return '';return `<form class="v953-card" data-rem-form><div class="v953-toolbar"><div><h3 class="v953-title-sm">${r.id?'Editar lembrete':'Novo lembrete'}</h3><p class="v953-muted">Crie um lembrete manual ou vinculado a um lead.</p></div><button type="button" class="v953-btn small" data-cancel-reminder>Fechar</button></div><div class="v953-form-grid"><label>Título<input class="v953-field" data-rem-title value="${esc(r.title||'')}"></label><label>Tipo<select class="v953-select" data-rem-type>${Object.keys(REM_TYPES).map(k=>`<option value="${k}" ${r.type===k?'selected':''}>${REM_TYPES[k]}</option>`).join('')}</select></label><label>Lead<select class="v953-select" data-rem-lead><option value="">Sem lead vinculado</option>${leads.map(l=>`<option value="${esc(l.id)}" ${r.leadId===l.id?'selected':''}>${esc(l.empresa)}</option>`).join('')}</select></label><label>Prioridade<select class="v953-select" data-rem-priority>${['Baixa','Média','Alta','Urgente'].map(p=>`<option ${r.priority===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Data<input class="v953-field" type="date" data-rem-date value="${esc(r.dueDate||today())}"></label><label>Hora<input class="v953-field" type="time" data-rem-time value="${esc(r.dueTime||'09:00')}"></label><label>Repetição<select class="v953-select" data-rem-rec>${['none','daily','weekly','monthly'].map(v=>`<option value="${v}" ${r.recurrence===v?'selected':''}>${v==='none'?'Não repetir':v==='daily'?'Diário':v==='weekly'?'Semanal':'Mensal'}</option>`).join('')}</select></label><label>Canal<select class="v953-select" data-rem-channel>${Object.keys(REM_TYPES).map(k=>`<option value="${k}" ${r.channel===k?'selected':''}>${REM_TYPES[k]}</option>`).join('')}</select></label></div><label>Observação<textarea class="v953-textarea" data-rem-note>${esc(r.note||'')}</textarea></label><div class="v953-actions"><button type="button" class="v953-btn primary" data-save-reminder>Salvar lembrete</button></div></form>`}
 function reminderCard(r){const lead=getLead(r.leadId);const dueClass=isOverdue(r)?'overdue':isToday(r)?'today':'';return `<article class="v953-reminder"><div class="v953-reminder-icon">${REM_ICONS[r.type]||'🔔'}</div><div class="v953-reminder-main"><b>${esc(r.title)}</b><p>${esc(lead?lead.empresa:'Sem lead vinculado')} · ${esc(REM_TYPES[r.type]||r.type)} · <span class="v953-due ${dueClass}">${esc(formatDateTime(r.dueDate,r.dueTime))}</span></p>${r.note?`<p>${esc(r.note)}</p>`:''}<div class="v953-reminder-meta"><span class="v953-pill ${r.priority==='Alta'||r.priority==='Urgente'?'warn':'gray'}">${esc(r.priority)}</span>${r.recurrence!=='none'?`<span class="v953-pill ok">${esc(r.recurrence)}</span>`:''}${r.status==='done'?'<span class="v953-pill ok">Concluído</span>':''}</div></div><div class="v953-actions"><button class="v953-btn small" data-edit-rem="${esc(r.id)}">Editar</button>${r.status!=='done'?`<button class="v953-btn small primary" data-done-rem="${esc(r.id)}">Concluir</button><button class="v953-btn small" data-snooze-rem="${esc(r.id)}">Adiar</button><button class="v953-btn small soft" data-notify-rem="${esc(r.id)}">Notificar</button>`:''}<button class="v953-btn small" data-open-lead="${esc(r.leadId||'')}">Abrir lead</button></div></article>`}
 function historyView(){const hist=getHistory();return `<section class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Histórico</h2><p class="v953-muted">Execuções do motor, testes, lembretes concluídos e ações automáticas.</p></div><button class="v953-btn danger" data-clear-history>Limpar histórico</button></div><div class="v953-grid">${hist.length?hist.slice(0,80).map(logItem).join(''):'<div class="v953-empty">Ainda não há histórico.</div>'}</div></section>`}
 function logItem(h){return `<div class="v953-log"><div class="v953-log-time">${esc(formatDate(h.at))}</div><div class="v953-log-main"><b>${esc(h.ruleName||h.title||triggerLabels[h.eventType]||h.kind||'Evento')}</b><span>${esc((h.kind||'registro')+' · '+(h.eventType?triggerLabels[h.eventType]||h.eventType:'manual')+' · '+Number(h.affected||0)+' lead(s)')}</span>${h.sample&&h.sample.length?`<span>${esc(h.sample.join(', '))}</span>`:''}</div><span class="v953-pill ${h.kind==='test'?'warn':h.status==='undone'?'danger':'ok'}">${esc(h.kind||'log')}</span></div>`}
 function settingsView(){const s=getSettings();return `<section class="v953-panel"><h2 class="v953-title-sm">Configurações de lembretes</h2><p class="v953-muted">Notificações internas funcionam com o CRM aberto. Notificações do navegador podem ser ativadas depois, conforme permissão do navegador.</p><div class="v953-form-grid"><label>Horário padrão<input class="v953-field" type="time" data-setting="defaultReminderTime" value="${esc(s.defaultReminderTime)}"></label><label>Alertar antes de quantos minutos<input class="v953-field" type="number" data-setting="toastBeforeMinutes" value="${esc(s.toastBeforeMinutes)}"></label><label class="v953-switch"><input type="checkbox" data-setting-check="summaryOnOpen" ${s.summaryOnOpen?'checked':''}> Mostrar resumo ao abrir</label><label class="v953-switch"><input type="checkbox" data-setting-check="browserNotifications" ${s.browserNotifications?'checked':''}> Preparar notificações do navegador</label></div><div class="v953-actions"><button class="v953-btn primary" data-save-settings>Salvar configurações</button><button class="v953-btn" data-request-browser-notif>Permitir notificação do navegador</button><button class="v953-btn" data-reset-reminders>Recriar lembretes de exemplo</button></div></section><section class="v953-panel"><div class="v953-toolbar"><div><h2 class="v953-title-sm">Notificações internas</h2><p class="v953-muted">Alertas gerados por lembretes e automações.</p></div><button class="v953-btn small" data-clear-read>Marcar todas como lidas</button></div>${notificationsList(40)}</section>`}
 function notificationsList(limit){const n=getNotifs().slice(0,limit||20);return `<div class="v953-grid">${n.length?n.map(x=>`<div class="v953-notif ${x.read?'':'unread'}"><div><b>${esc(x.title)}</b><p class="v953-muted">${esc(x.body||'')} · ${esc(formatDate(x.createdAt))}</p></div><button class="v953-btn small" data-read-notif="${esc(x.id)}">${x.read?'Lida':'Marcar lida'}</button></div>`).join(''):'<div class="v953-empty">Nenhuma notificação interna.</div>'}</div>`}
 function activateRecipe(id,copyOnly){const r=RECIPES.find(x=>x.id===id);if(!r)return;const rules=getRules();const rule={id:uid('rule'),name:r.title,desc:r.desc,category:r.cat,active:!copyOnly,trigger:r.trigger,conditions:JSON.parse(JSON.stringify(r.conditions)),actions:JSON.parse(JSON.stringify(r.actions)),createdAt:nowISO(),version:VERSION};rules.unshift(rule);saveRules(rules);addHistory({kind:'recipe',ruleName:rule.name,eventType:rule.trigger,affected:0,status:copyOnly?'copy':'activated'});toast(copyOnly?'Receita copiada':'Receita ativada',rule.name);activeTab='rules';render()}
 function testRecipe(id){const r=RECIPES.find(x=>x.id===id);if(!r)return;let res={affected:0};try{res=window.CRMV952RuleEngine.testRule({id:r.id,name:r.title,trigger:r.trigger,conditions:r.conditions,actions:r.actions})}catch(e){}toast('Teste da receita',`${Number(res.affected||0)} lead(s) seriam impactados.`)}
 function toggleRule(id){const rules=getRules();const r=rules.find(x=>x.id===id);if(r){r.active=r.active===false;saveRules(rules);toast(r.active===false?'Automação pausada':'Automação ativada',r.name);render()}}
 function runRule(id){const r=getRules().find(x=>x.id===id);if(!r)return;let res={affected:0};try{res=window.CRMV952RuleEngine.runRule(r,r.trigger||'manual_run',{}, {force:true})}catch(e){}toast('Automação executada',`${Number(res.affected||0)} lead(s) impactado(s).`);render()}
 function testRule(id){const r=getRules().find(x=>x.id===id);if(!r)return;let res={affected:0};try{res=window.CRMV952RuleEngine.testRule(r)}catch(e){}toast('Teste realizado',`${Number(res.affected||0)} lead(s) seriam impactados.`)}
 function deleteRule(id){const rules=getRules().filter(x=>x.id!==id);saveRules(rules);toast('Automação excluída');render()}
 function newReminder(){editReminderId=uid('new');const arr=getReminders();arr.unshift(normalizeReminder({id:editReminderId,title:'Novo lembrete',type:'followup',dueDate:today(),dueTime:getSettings().defaultReminderTime,status:'draft'}));saveReminders(arr);activeTab='reminders';reminderFilter='today';render()}
 function saveReminderFromForm(){const root=$('#automacoes');const arr=getReminders();let id=editReminderId;let idx=arr.findIndex(r=>r.id===id);if(idx<0){id=uid('rem');idx=0;arr.unshift({id})}const r=arr[idx];r.title=($('[data-rem-title]',root)||{}).value||'Lembrete';r.type=($('[data-rem-type]',root)||{}).value||'followup';r.leadId=($('[data-rem-lead]',root)||{}).value||'';r.priority=($('[data-rem-priority]',root)||{}).value||'Média';r.dueDate=($('[data-rem-date]',root)||{}).value||today();r.dueTime=($('[data-rem-time]',root)||{}).value||'09:00';r.recurrence=($('[data-rem-rec]',root)||{}).value||'none';r.channel=($('[data-rem-channel]',root)||{}).value||r.type;r.note=($('[data-rem-note]',root)||{}).value||'';r.status='active';r.updatedAt=nowISO();saveReminders(arr);addHistory({kind:'reminder',title:r.title,affected:r.leadId?1:0,status:'saved'});editReminderId=null;toast('Lembrete salvo',r.title);render()}
 function completeReminder(id){const arr=getReminders();const r=arr.find(x=>x.id===id);if(!r)return;if(r.recurrence&&r.recurrence!=='none'){const d=new Date(r.dueDate+'T'+(r.dueTime||'09:00'));if(r.recurrence==='daily')d.setDate(d.getDate()+1);if(r.recurrence==='weekly')d.setDate(d.getDate()+7);if(r.recurrence==='monthly')d.setMonth(d.getMonth()+1);r.dueDate=d.toISOString().slice(0,10);r.notifiedAt='';r.completedAt=nowISO();addHistory({kind:'reminder',title:r.title,affected:r.leadId?1:0,status:'rescheduled',sample:['Reagendado por repetição']});toast('Lembrete reagendado',r.title)}else{r.status='done';r.completedAt=nowISO();addHistory({kind:'reminder',title:r.title,affected:r.leadId?1:0,status:'done'});toast('Lembrete concluído',r.title)}saveReminders(arr);render()}
 function snoozeReminder(id){const arr=getReminders();const r=arr.find(x=>x.id===id);if(!r)return;r.dueDate=tomorrow();r.dueTime=r.dueTime||getSettings().defaultReminderTime;r.notifiedAt='';r.status='active';saveReminders(arr);addHistory({kind:'reminder',title:r.title,affected:r.leadId?1:0,status:'snoozed'});toast('Lembrete adiado para amanhã',r.title);render()}
 function notifyReminder(id){const r=getReminders().find(x=>x.id===id);if(!r)return;const lead=getLead(r.leadId);addNotif('Lembrete: '+r.title,(lead?lead.empresa+' · ':'')+formatDateTime(r.dueDate,r.dueTime),r.leadId);r.notifiedAt=nowISO();saveReminders(getReminders().map(x=>x.id===id?r:x));render()}
 function syncRemindersFromLeads(){const leads=getLeads();const arr=getReminders();let created=0;const existing=new Set(arr.map(r=>r.leadId+'_'+r.dueDate+'_'+r.type));leads.forEach(l=>{if(!l.proximaData)return;const type=/whats/i.test(l.proximaAcao||'')?'whatsapp':/reuni/i.test(l.proximaAcao||'')?'meeting':'followup';const key=l.id+'_'+l.proximaData+'_'+type;if(existing.has(key))return;arr.push(normalizeReminder({title:(l.proximaAcao||'Follow-up')+' — '+l.empresa,type,leadId:l.id,dueDate:l.proximaData,dueTime:l.proximaHora||getSettings().defaultReminderTime,priority:l.prioridade||'Média',note:'Gerado pela próxima ação do lead.'}));created++});saveReminders(arr);toast('Lembretes sincronizados',created+' novo(s) lembrete(s).');render()}
 function checkDueReminders(showToast){const arr=getReminders();let changed=false, count=0;arr.forEach(r=>{if(r.status==='done')return;if((isOverdue(r)||isSoon(r))&&!r.notifiedAt){const lead=getLead(r.leadId);addNotif((isOverdue(r)?'Vencido: ':'Próximo: ')+r.title,(lead?lead.empresa+' · ':'')+formatDateTime(r.dueDate,r.dueTime),r.leadId);r.notifiedAt=nowISO();changed=true;count++}});if(changed)saveReminders(arr);if(showToast)toast('Verificação concluída',count+' lembrete(s) geraram notificação.');return count}
 function clearRead(){const n=getNotifs().map(x=>Object.assign({},x,{read:true}));saveNotifs(n);toast('Notificações marcadas como lidas');render()}
 function saveSettingsFromUI(){const root=$('#automacoes');const s={};$$('[data-setting]',root).forEach(i=>{s[i.dataset.setting]=i.type==='number'?Number(i.value||0):i.value});$$('[data-setting-check]',root).forEach(i=>{s[i.dataset.settingCheck]=!!i.checked});saveSettings(s);toast('Configurações salvas');render()}
 function requestBrowserNotif(){if(!('Notification' in window)){toast('Navegador não suporta Notification API');return}Notification.requestPermission().then(p=>{saveSettings({browserNotifications:p==='granted'});toast(p==='granted'?'Notificações permitidas':'Permissão não concedida')})}
 function openLead(leadId){if(!leadId){toast('Este lembrete não tem lead vinculado');return}try{if(window.CRMV94Official&&typeof window.CRMV94Official.openLead==='function'){window.CRMV94Official.openLead(leadId);return}}catch(e){}location.hash='#leads';setTimeout(()=>toast('Lead vinculado',getLead(leadId)?.empresa||leadId),120)}
 function bindRoot(root){if(root.dataset.v953Bound)return;root.dataset.v953Bound='1';root.addEventListener('input',e=>{if(e.target.matches('[data-search-recipes]')){recipeSearch=e.target.value;render()}});root.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;
   if(t.dataset.v953Tab){activeTab=t.dataset.v953Tab;render();return}
   if(t.dataset.recipeCat){const c=t.dataset.recipeCat;recipeSearch=c==='Todos'?'':c;render();return}
   if(t.dataset.activateRecipe){activateRecipe(t.dataset.activateRecipe,false);return}
   if(t.dataset.copyRecipe){activateRecipe(t.dataset.copyRecipe,true);return}
   if(t.dataset.testRecipe){testRecipe(t.dataset.testRecipe);return}
   if(t.dataset.toggleRule){toggleRule(t.dataset.toggleRule);return}
   if(t.dataset.runRule){runRule(t.dataset.runRule);return}
   if(t.dataset.testRule){testRule(t.dataset.testRule);return}
   if(t.dataset.deleteRule){deleteRule(t.dataset.deleteRule);return}
   if(t.hasAttribute('data-run-system')){try{window.CRMV952RuleEngine.runSystemChecks()}catch(e){}checkDueReminders(true);return}
   if(t.hasAttribute('data-undo-last')){try{window.CRMV952RuleEngine.undoLast()}catch(e){toast('Não encontrei execução para desfazer')}return}
   if(t.hasAttribute('data-simulate-event')){const ev=($('[data-event-select]',root)||{}).value||'manual_run';try{const res=window.CRMV952RuleEngine.emit(ev,{});toast('Evento simulado',`${res.rules||0} regra(s), ${res.affected||0} lead(s).`)}catch(e){toast('Não foi possível simular evento')}render();return}
   if(t.dataset.remFilter){reminderFilter=t.dataset.remFilter;editReminderId=null;render();return}
   if(t.hasAttribute('data-new-reminder')){newReminder();return}
   if(t.dataset.editRem){editReminderId=t.dataset.editRem;activeTab='reminders';render();return}
   if(t.hasAttribute('data-cancel-reminder')){if(editReminderId){let arr=getReminders();const r=arr.find(x=>x.id===editReminderId);if(r&&r.status==='draft')saveReminders(arr.filter(x=>x.id!==editReminderId))}editReminderId=null;render();return}
   if(t.hasAttribute('data-save-reminder')){saveReminderFromForm();return}
   if(t.dataset.doneRem){completeReminder(t.dataset.doneRem);return}
   if(t.dataset.snoozeRem){snoozeReminder(t.dataset.snoozeRem);return}
   if(t.dataset.notifyRem){notifyReminder(t.dataset.notifyRem);return}
   if(t.dataset.openLead!==undefined){openLead(t.dataset.openLead);return}
   if(t.hasAttribute('data-sync-reminders')){syncRemindersFromLeads();return}
   if(t.hasAttribute('data-check-reminders')){checkDueReminders(true);render();return}
   if(t.hasAttribute('data-clear-read')){clearRead();return}
   if(t.dataset.readNotif){const n=getNotifs().map(x=>x.id===t.dataset.readNotif?Object.assign({},x,{read:true}):x);saveNotifs(n);render();return}
   if(t.hasAttribute('data-clear-history')){writeJSON(HIST_KEY,[]);toast('Histórico limpo');render();return}
   if(t.hasAttribute('data-save-settings')){saveSettingsFromUI();return}
   if(t.hasAttribute('data-request-browser-notif')){requestBrowserNotif();return}
   if(t.hasAttribute('data-reset-reminders')){saveReminders(seedReminders());toast('Lembretes recriados');render();return}
 });}
 function route(){activeTab=activeTab||'overview';render()}
 function boot(){D.body&&D.body.classList.add('v953-automations-ready');window.CRMV953RemindersCenter={version:VERSION,render,route,checkDueReminders,getReminders,saveReminders,addNotif};window.CRMV95Automations=Object.assign(window.CRMV95Automations||{},{render,route,version:VERSION});window.renderAutomations=render;if(window.CRMV94Official&&window.CRMV94Official.map)window.CRMV94Official.map.automacoes='V95.3 Central de Lembretes';setInterval(()=>checkDueReminders(false),60000);setTimeout(()=>{const active=(location.hash||'').replace('#','')||($('.view.active')&&$('.view.active').id)||'';const el=$('#automacoes');if(active==='automacoes'||(el&&/Carregando módulo|Automações de funil|Motor interno/i.test(el.textContent||'')))render();else checkDueReminders(false)},340)}
 if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
