(function(){
'use strict';
if(window.CRMV990Ligacoes) return;

const VERSION='99.0';
const LEADS_KEY='crm_v99_leads';
const UI_KEY='crm_v987_ligacoes_ui';
const LEGACY_UI_KEY='crm_v982_ligacoes_ui';
const UNDO_KEY='crm_v987_last_call_undo';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const readJSON=(k,fb)=>{try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):fb}catch(e){return fb}};
const writeJSON=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){console.warn('[CRM Ligações] Falha ao salvar',e);return false}};
const clone=v=>JSON.parse(JSON.stringify(v));
const pad=n=>String(Math.max(0,Number(n)||0)).padStart(2,'0');
const today=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const money=v=>{try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(Number(v)||0)}catch(e){return 'R$ '+(Number(v)||0)}};
const engine=()=>window.CRMScriptEngine;
let timer=null,startedAt=0,elapsedBefore=0,paused=false,registering=false,noteTimer=null,ownerTimer=null;

function baseFocus(){return{leftOpen:true,rightOpen:true,rightTab:'objections',distraction:false,activeBlockId:'',objectSearch:'',objectCategory:'Todos',editor:false,editorBlockId:'',queueCompact:false}}
function defaultState(){return{routine:false,currentId:null,selectedId:null,filter:'todos',search:'',processed:[],session:null,summary:null,singleComplete:null,pendingDialog:null,focus:baseFocus()}}
function state(){
  const legacy=readJSON(LEGACY_UI_KEY,{}),raw=readJSON(UI_KEY,null),source=raw&&typeof raw==='object'?raw:(legacy&&typeof legacy==='object'?legacy:{});
  const out=Object.assign(defaultState(),source);out.focus=Object.assign(baseFocus(),source.focus||{});out.processed=Array.isArray(out.processed)?out.processed:[];
  if(out.session&&typeof out.session==='object'){
    out.session.queueIds=Array.isArray(out.session.queueIds)?out.session.queueIds:[];
    out.session.entries=Array.isArray(out.session.entries)?out.session.entries:[];
    out.session.skipped=Array.isArray(out.session.skipped)?out.session.skipped:[];
    out.session.responses=out.session.responses&&typeof out.session.responses==='object'?out.session.responses:{};
    out.session.objections=Array.isArray(out.session.objections)?out.session.objections:[];
  }
  return out;
}
function saveState(s){writeJSON(UI_KEY,Object.assign(defaultState(),s||{}))}
function leadName(l){return l?.empresa||l?.nome||l?.name||'Lead sem nome'}
function getStage(l){return l?.followupEtapa||l?.followupStage||l?.followup||'Primeiro contato'}
function getDate(l){return l?.proximaData||l?.nextDate||l?.followupData||''}
function getTime(l){return l?.proximaHora||l?.nextTime||l?.followupHora||''}
function normLead(l){
  l=Object.assign({},l||{});const pipe=window.CRMStageRegistry?.resolveStage?.(l,{create:true});const pipeline=pipe?.name||l.pipeline||l.etapa||'Lead';
  return Object.assign(l,{id:l.id||('lead_'+Math.random().toString(36).slice(2)),nome:l.nome||l.empresa||'Lead sem nome',empresa:l.empresa||l.nome||'Lead sem nome',pipelineStageId:pipe?.id||l.pipelineStageId,pipeline,etapa:pipeline,followup:getStage(l),followupEtapa:getStage(l),proximaData:getDate(l),followupData:getDate(l),proximaHora:getTime(l),followupHora:getTime(l),prioridade:l.prioridade||'Média',responsavel:l.responsavel||'Você',historico:Array.isArray(l.historico)?l.historico:[],objecoesHistorico:Array.isArray(l.objecoesHistorico)?l.objecoesHistorico:[],contatos:Number(l.contatos||0),ligacoes:Number(l.ligacoes||0),whatsapps:Number(l.whatsapps||0),tempoLigacoesSegundos:Number(l.tempoLigacoesSegundos||0),callWorkspace:l.callWorkspace&&typeof l.callWorkspace==='object'?l.callWorkspace:{notes:{},blockNotes:{},answers:{}}});
}
function getLeads(){const arr=window.CRMData?.leads?.all?.()||window.CRMCommercialModel?.getLeads?.()||[];const list=Array.isArray(arr)?arr.map(normLead):[];window.CRMStageRegistry?.migrateLeads?.(list);return list}
function saveLeads(list,source='ligacoes-v99'){const normalized=list.map(normLead);return window.CRMData?.leads?.save?.(normalized,source)||normalized}
function patchLead(id,mutator,source='ligacoes-v98.7'){const list=getLeads(),i=list.findIndex(l=>l.id===id);if(i<0)return null;mutator(list[i]);list[i]=normLead(list[i]);saveLeads(list,source);return list[i]}
function choosePB(l){return engine()?.choosePlaybook(l)||null}
function blocks(pb){return (pb?.scriptBlocks||[]).filter(b=>!b.hidden)}
function fill(text,l){return engine()?.fill(text,l)||String(text||'')}
function phoneInfo(l){return window.CRMStageRegistry?.phoneInfo?.(l)||{valid:!!String(l?.telefone||'').replace(/\D/g,''),href:l?.telefone?'tel:'+l.telefone:'#',whatsapp:'#',reason:'Telefone inválido'}}
function notify(msg,type='success'){try{if(window.crmToast)return window.crmToast(msg,type);if(window.showToast)return window.showToast(msg,type)}catch(e){}let t=$('#v987CallToast');if(!t){t=document.createElement('div');t.id='v987CallToast';t.className='v987-toast';document.body.appendChild(t)}t.textContent=msg;t.className='v987-toast '+type;t.hidden=false;clearTimeout(t._tm);t._tm=setTimeout(()=>t.hidden=true,2900)}
function score(l){let s=0,d=getDate(l);if(d&&d<today())s+=45;if(d===today())s+=30;if(!d)s+=14;s+=({Alta:30,'Média':18,Media:18,Baixa:8}[l.prioridade]||12);s+=Math.min(22,Math.round(Number(l.valor||0)/1000)*3);if(!l.ligacoes)s+=12;if(/retorno/i.test(getStage(l)))s+=18;if(/garimpo/i.test([l.origem,l.campanha,l.fonte,l.source].join(' ')))s+=5;return Math.min(100,s)}
function reason(l){const d=getDate(l);if(d&&d<today())return 'Follow-up vencido';if(d===today())return 'Contato programado para hoje';if(/retorno/i.test(getStage(l)))return 'Retorno combinado';if(!l.ligacoes)return 'Primeira tentativa';if(l.prioridade==='Alta')return 'Prioridade alta';return 'Próxima oportunidade da fila'}
function isGarimpo(l){return /garimpo|prospec[cç][aã]o|miner/i.test([l.origem,l.campanha,l.fonte,l.source,l.tags,l.observacoes,l.obs].join(' '))||l.garimpo===true}
function matchesFilter(l,f){if(f==='hoje')return getDate(l)===today();if(f==='vencidas')return !!getDate(l)&&getDate(l)<today();if(f==='sem')return Number(l.ligacoes||0)===0;if(f==='retornos')return /retorno/i.test(getStage(l))||/retorno/i.test(l.proximaAcao||'');if(f==='garimpo')return isGarimpo(l);return true}
function baseQueue(){return getLeads().filter(l=>window.CRMStageRegistry?.isOpenLead?.(l)!==false)}
function queue(filterOverride){const st=state(),q=norm(st.search),f=filterOverride||st.filter||'todos';return baseQueue().filter(l=>{if(q&&!norm([leadName(l),l.telefone,l.cidade,l.segmento,l.origem,l.campanha,l.tags,l.responsavel].join(' ')).includes(q))return false;return matchesFilter(l,f)}).sort((a,b)=>score(b)-score(a)||String(getDate(a)||'9999').localeCompare(String(getDate(b)||'9999')))}
function filterCounts(){return Object.fromEntries(['todos','hoje','vencidas','sem','retornos','garimpo'].map(f=>[f,queue(f).length]))}
function routineList(){const st=state(),all=getLeads();if(st.routine&&st.session?.queueIds?.length)return st.session.queueIds.map(id=>all.find(l=>l.id===id)).filter(Boolean);return queue()}
function currentLead(){const st=state(),list=st.routine?routineList():queue();return list.find(l=>l.id===st.currentId)||list.find(l=>l.id===st.selectedId)||list[0]||null}
function durationSeconds(){if(!startedAt)return elapsedBefore;return elapsedBefore+(paused?0:Math.floor((Date.now()-startedAt)/1000))}
function formatDuration(s){s=Math.max(0,Math.round(Number(s)||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${pad(h)}:${pad(m)}:${pad(sec)}`:`${pad(m)}:${pad(sec)}`}
function stopTimer(){clearInterval(timer);timer=null;startedAt=0;elapsedBefore=0;paused=false}
function saveTimerSnapshot(forcePaused=paused){const st=state();if(!st.routine||!st.session)return;st.session.timerElapsed=durationSeconds();st.session.timerPaused=!!forcePaused;saveState(st)}
function pauseAndPersist(){elapsedBefore=durationSeconds();paused=true;startedAt=0;clearInterval(timer);timer=null;saveTimerSnapshot(true);updateTimer()}
function startTimer(reset=true){clearInterval(timer);if(reset){elapsedBefore=0;startedAt=Date.now();paused=false}else if(!paused)startedAt=Date.now();timer=setInterval(updateTimer,500);saveTimerSnapshot(false);updateTimer()}
function restoreTimer(st){const session=st?.session||{};if(Object.prototype.hasOwnProperty.call(session,'timerElapsed')){elapsedBefore=Number(session.timerElapsed||0);paused=session.timerPaused!==false;startedAt=paused?0:Date.now();clearInterval(timer);timer=paused?null:setInterval(updateTimer,500);updateTimer();return true}return false}
function updateTimer(){const el=$('#v987CallTimer');if(el)el.textContent=formatDuration(durationSeconds())}
function toggleTimer(){if(paused){paused=false;startedAt=Date.now();startTimer(false)}else pauseAndPersist();saveTimerSnapshot(paused);const b=$('[data-v987-timer="pause"]');if(b)b.textContent=paused?'Continuar':'Pausar'}
function whatsappText(l){const pb=choosePB(l),b=blocks(pb).find(x=>x.id==='whatsapp'||/whats/i.test(x.title));return fill(b?.content||pb?.script?.whatsapp||'',l)}
function whatsappHref(l){const p=phoneInfo(l);return p.valid?`${p.whatsapp}?text=${encodeURIComponent(whatsappText(l))}`:'#'}
function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text||'').catch(()=>fallback());fallback();return Promise.resolve();function fallback(){const ta=document.createElement('textarea');ta.value=text||'';ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy')}catch(e){}ta.remove()}}
function callMetrics(){const events=getLeads().flatMap(l=>(l.historico||[]).filter(e=>norm(e.tipo).includes('ligacao'))),withD=events.filter(e=>Number(e.duracaoSegundos||e.duracao)>0),total=withD.reduce((s,e)=>s+Number(e.duracaoSegundos||e.duracao||0),0);return{total:events.length,average:withD.length?Math.round(total/withD.length):0}}

function workspace(l){return Object.assign({notes:{summary:'',pain:'',need:'',budget:'',deadline:'',decisionMaker:'',competitor:'',interest:'Médio',general:''},blockNotes:{},answers:{}},l?.callWorkspace||{})}
function saveWorkspaceField(leadId,kind,key,value){clearTimeout(noteTimer);noteTimer=setTimeout(()=>{patchLead(leadId,l=>{l.callWorkspace=workspace(l);if(kind==='note')l.callWorkspace.notes[key]=value;if(kind==='blockNote')l.callWorkspace.blockNotes[key]=value;if(kind==='answer')l.callWorkspace.answers[key]=value;l.callWorkspace.updatedAt=new Date().toISOString()},'ligacoes-workspace')},220)}
function saveAnswer(block,value,label){const l=currentLead(),st=state();if(!l||!block)return;const answer={value,label:label||value,at:new Date().toISOString(),blockTitle:block.title};saveWorkspaceField(l.id,'answer',block.id,answer);st.session=st.session||{};st.session.responses=st.session.responses||{};st.session.responses[block.id]=answer;saveState(st)}
function activeBlock(pb,st){const list=blocks(pb);let id=st.focus.activeBlockId;if(!list.some(b=>b.id===id))id=list[0]?.id||'';return list.find(b=>b.id===id)||list[0]||null}
function setActiveBlock(id){const st=state();st.focus.activeBlockId=id;saveState(st);render()}
function adjacentBlock(direction){const l=currentLead(),pb=choosePB(l),list=blocks(pb),st=state(),cur=activeBlock(pb,st),i=list.findIndex(b=>b.id===cur?.id),next=list[i+(direction==='prev'?-1:1)];if(next)setActiveBlock(next.id)}
function goFromOption(block,opt){saveAnswer(block,opt.value,opt.label);const pb=choosePB(currentLead()),list=blocks(pb),next=(opt.nextId&&list.find(b=>b.id===opt.nextId))||list[list.findIndex(b=>b.id===block.id)+1];if(next)setActiveBlock(next.id);else render()}

function historyHTML(l,limit=8){const events=(l.historico||[]).slice(-limit).reverse();return events.length?events.map(ev=>`<div class="v987-history-row"><i></i><div><b>${esc(ev.tipo||'Contato')} · ${esc(ev.resultado||'')}</b><span>${esc(ev.data||'')} ${esc(ev.hora||'')} ${Number(ev.duracaoSegundos||0)?'· '+esc(formatDuration(ev.duracaoSegundos)):''}</span><small>${esc(ev.obs||ev.nota||'Sem observação')}</small></div></div>`).join(''):'<div class="v987-empty">Sem histórico registrado.</div>'}
function queueCard(l,i,current){const p=phoneInfo(l);return `<article class="v987-queue-card ${current?'active':''}"><button type="button" data-v987-select="${esc(l.id)}"><span>${i+1}</span><div><b>${esc(leadName(l))}</b><small>${esc(reason(l))}</small><em>${esc(l.cidade||l.segmento||'Sem local')} · ${esc(getDate(l)||'sem data')} ${esc(getTime(l))}</em></div><strong>${score(l)}</strong></button><div><a class="${p.valid?'':'disabled'}" href="${esc(whatsappHref(l))}" ${p.valid?'target="_blank" rel="noopener"':''}>WhatsApp</a></div></article>`}
function leadContextHTML(l,list,index){const p=phoneInfo(l);return `<section class="v987-side-section v987-lead-context"><div class="v987-side-head"><span>Lead atual</span><button type="button" data-v987-toggle-left title="Recolher painel">×</button></div><div class="v987-lead-title"><div><h2>${esc(leadName(l))}</h2><p>${esc(l.segmento||'Sem segmento')} · ${esc(l.cidade||'Sem cidade')}</p></div><strong>${score(l)}</strong></div>${p.valid?'':`<div class="v987-warning">${esc(p.reason)}</div>`}<div class="v987-info-grid"><div><span>Telefone</span><b>${esc(l.telefone||'Sem telefone')}</b></div><div><span>Pipeline</span><b>${esc(l.pipeline)}</b></div><div><span>Follow-up</span><b>${esc(getStage(l))}</b></div><div><span>Próxima ação</span><b>${esc(l.proximaAcao||'Não definida')}</b></div><div><span>Valor</span><b>${esc(money(l.valor))}</b></div><div><span>Tentativas</span><b>${Number(l.ligacoes||0)}</b></div></div><div class="v987-lead-actions"><a class="v987-action primary ${p.valid?'':'disabled'}" href="${esc(p.href)}">Ligar</a><a class="v987-action ${p.valid?'':'disabled'}" href="${esc(whatsappHref(l))}" ${p.valid?'target="_blank" rel="noopener"':''}>WhatsApp</a><button class="v987-action" type="button" data-v987-open-lead="${esc(l.id)}">Ficha</button></div></section><section class="v987-side-section v987-mini-history"><h3>Histórico recente</h3>${historyHTML(l,4)}</section><section class="v987-side-section v987-routine-queue"><div class="v987-side-head"><div><span>Fila da rotina</span><small>${index+1} de ${list.length}</small></div></div><div class="v987-queue-mini">${list.map((x,i)=>queueCard(x,i,x.id===l.id)).join('')}</div></section>`}
function leadPreviewHTML(l){const p=phoneInfo(l);return `<section class="v987-side-section v987-lead-context v989-lead-preview"><div class="v987-side-head"><span>Lead selecionado</span></div><div class="v987-lead-title"><div><h2>${esc(leadName(l))}</h2><p>${esc(l.segmento||'Sem segmento')} · ${esc(l.cidade||'Sem cidade')}</p></div><strong>${score(l)}</strong></div>${p.valid?'':`<div class="v987-warning">${esc(p.reason)}</div>`}<div class="v987-info-grid"><div><span>Telefone</span><b>${esc(l.telefone||'Sem telefone')}</b></div><div><span>Pipeline</span><b>${esc(l.pipeline)}</b></div><div><span>Follow-up</span><b>${esc(getStage(l))}</b></div><div><span>Próxima ação</span><b>${esc(l.proximaAcao||'Não definida')}</b></div><div><span>Valor</span><b>${esc(money(l.valor))}</b></div><div><span>Tentativas</span><b>${Number(l.ligacoes||0)}</b></div></div><div class="v987-lead-actions"><a class="v987-action primary ${p.valid?'':'disabled'}" href="${esc(p.href)}">Ligar</a><a class="v987-action ${p.valid?'':'disabled'}" href="${esc(whatsappHref(l))}" ${p.valid?'target="_blank" rel="noopener"':''}>WhatsApp</a><button class="v987-action" type="button" data-v987-open-lead="${esc(l.id)}">Ficha</button></div></section><section class="v987-side-section v987-mini-history"><h3>Histórico recente</h3>${historyHTML(l,4)}</section>`}
function blockTypeIcon(type){return{'speech':'Fala','question-single':'Escolha','question-multi':'Múltipla','checklist':'Checklist','notice':'Aviso','proof':'Prova','action':'Ação'}[type]||'Bloco'}
function blockRuntimeHTML(block,l,ws){
  if(!block)return'<div class="v987-empty">O Playbook não possui blocos.</div>';
  const answer=ws.answers?.[block.id],filled=fill(block.content,l),note=ws.blockNotes?.[block.id]||'';
  let body='';
  if(['speech','notice','proof','action'].includes(block.type))body=`<div class="v987-script-copy ${block.type}">${filled.split(/\n+/).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')||'<p>Sem conteúdo neste bloco.</p>'}</div>`;
  if(block.type==='question-single')body=`<div class="v987-question"><p>${esc(filled)}</p><div class="v987-answer-grid">${(block.options||[]).map(o=>`<button type="button" class="${answer?.value===o.value?'selected':''}" data-v987-answer="${esc(block.id)}" data-option-id="${esc(o.id)}">${esc(o.label)}</button>`).join('')}</div></div>`;
  if(block.type==='question-multi'||block.type==='checklist'){const values=Array.isArray(answer?.value)?answer.value:[];body=`<div class="v987-question"><p>${esc(filled)}</p><div class="v987-check-grid">${(block.options||[]).map(o=>`<label><input type="checkbox" data-v987-multi-answer="${esc(block.id)}" value="${esc(o.value)}" ${values.includes(o.value)?'checked':''}><span>${esc(o.label)}</span></label>`).join('')}</div></div>`}
  return `<article class="v987-active-block"><div class="v987-block-meta"><span>${esc(blockTypeIcon(block.type))}</span>${block.required?'<b>Obrigatório</b>':''}</div><h1>${esc(block.title)}</h1>${block.objective?`<div class="v987-objective"><span>Objetivo desta etapa</span><b>${esc(block.objective)}</b></div>`:''}${body}<label class="v987-block-note"><span>${esc(block.notePrompt||'Nota desta etapa')}</span><textarea data-v987-block-note="${esc(block.id)}" placeholder="Registre o que o lead respondeu ou algo importante...">${esc(note)}</textarea></label></article>`
}
function scriptCenterHTML(l,pb,st){
  const list=blocks(pb),active=activeBlock(pb,st),index=Math.max(0,list.findIndex(b=>b.id===active?.id)),ws=workspace(l),progress=list.length?Math.round(((index+1)/list.length)*100):0;
  return `<section class="v987-script-center"><header class="v987-script-header"><div><span>Script em execução</span><h2>${esc(pb?.nome||'Playbook')}</h2><p>${esc(pb?.objetivo||'Conduza a conversa até um próximo passo claro.')}</p></div><div><button type="button" data-v987-open-studio>Editar roteiro</button><button type="button" data-v987-distraction>${st.focus.distraction?'Sair do foco':'Modo sem distrações'}</button></div></header><div class="v987-progress"><span style="width:${progress}%"></span></div><nav class="v987-block-nav">${list.map((b,i)=>`<button type="button" class="${b.id===active?.id?'active':''} ${ws.answers?.[b.id]?'done':''}" data-v987-block="${esc(b.id)}"><span>${i+1}</span><b>${esc(b.title)}</b></button>`).join('')}</nav>${blockRuntimeHTML(active,l,ws)}<footer class="v987-block-actions"><button type="button" data-v987-prev ${index===0?'disabled':''}>← Anterior</button><div><span>Etapa ${index+1} de ${list.length}</span><button type="button" data-v987-copy-block="${esc(active?.id||'')}">Copiar fala</button></div><button type="button" class="primary" data-v987-next ${index>=list.length-1?'disabled':''}>Próxima →</button></footer></section>`
}
function objectionResults(pb,l,st,block){
  const query=norm(st.focus.objectSearch),cat=st.focus.objectCategory||'Todos',items=(pb?.objecoes||[]).filter(o=>(cat==='Todos'||o.categoria===cat)&&(!query||norm([o.nome,o.categoria,o.resposta,o.pergunta,(o.frases||[]).join(' ')].join(' ')).includes(query)));
  return items.sort((a,b)=>(engine()?.objectionScore(b,{query,category:cat,lead:l,block})||0)-(engine()?.objectionScore(a,{query,category:cat,lead:l,block})||0));
}
function objectionCard(o){return `<article class="v987-objection-card"><div class="v987-objection-title"><div><span>${esc(o.categoria||'Geral')}</span><h4>${esc(o.nome)}</h4></div><button type="button" data-v987-copy-objection="${esc(o.id)}">Copiar</button></div><div class="v987-objection-part"><span>Resposta sugerida</span><p>${esc(o.resposta||'Sem resposta cadastrada.')}</p></div>${o.pergunta?`<div class="v987-objection-part"><span>Pergunta de aprofundamento</span><p>${esc(o.pergunta)}</p></div>`:''}${o.argumento?`<div class="v987-objection-part"><span>Argumento/prova</span><p>${esc(o.argumento)}</p></div>`:''}<div class="v987-objection-actions"><button type="button" data-v987-register-objection="${esc(o.id)}" data-status="apresentada">Registrar uso</button><button type="button" class="success" data-v987-register-objection="${esc(o.id)}" data-status="superada">Superada</button><button type="button" class="danger" data-v987-register-objection="${esc(o.id)}" data-status="nao-superada">Não superada</button></div></article>`}
function notesTabHTML(l){const n=workspace(l).notes||{};const fields=[['summary','Resumo da conversa','textarea'],['pain','Dor principal','input'],['need','Necessidade','input'],['budget','Orçamento','input'],['deadline','Prazo','input'],['decisionMaker','Decisor','input'],['competitor','Concorrente citado','input']];return `<div class="v987-notes-grid">${fields.map(([k,label,type])=>`<label class="${type==='textarea'?'wide':''}"><span>${label}</span>${type==='textarea'?`<textarea data-v987-note="${k}">${esc(n[k]||'')}</textarea>`:`<input data-v987-note="${k}" value="${esc(n[k]||'')}">`}</label>`).join('')}<label><span>Nível de interesse</span><select data-v987-note="interest">${['Baixo','Médio','Alto','Quente'].map(v=>`<option ${n.interest===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="wide"><span>Anotação livre</span><textarea data-v987-note="general">${esc(n.general||'')}</textarea></label></div>`}
function rightPanelHTML(l,pb,st,block){
  const tab=st.focus.rightTab||'objections',cats=engine()?.categories(pb)||['Todos'],items=objectionResults(pb,l,st,block);
  let body='';
  if(tab==='objections')body=`<div class="v987-objection-tools"><input data-v987-objection-search placeholder="Buscar objeção ou frase..." value="${esc(st.focus.objectSearch)}"><div>${cats.map(c=>`<button type="button" class="${st.focus.objectCategory===c?'active':''}" data-v987-objection-category="${esc(c)}">${esc(c)}</button>`).join('')}</div></div><div class="v987-objection-list">${items.map(objectionCard).join('')||'<div class="v987-empty">Nenhuma objeção encontrada.</div>'}</div>`;
  if(tab==='notes')body=notesTabHTML(l);
  if(tab==='history')body=`<div class="v987-full-history">${historyHTML(l,20)}</div>`;
  return `<aside class="v987-right-panel"><div class="v987-side-head"><span>Assistente comercial</span><button type="button" data-v987-toggle-right title="Recolher painel">×</button></div><nav><button type="button" class="${tab==='objections'?'active':''}" data-v987-right-tab="objections">Objeções</button><button type="button" class="${tab==='notes'?'active':''}" data-v987-right-tab="notes">Anotações</button><button type="button" class="${tab==='history'?'active':''}" data-v987-right-tab="history">Histórico</button></nav><div class="v987-right-body">${body}</div></aside>`
}
function outcomeBarHTML(){return `<footer class="v987-outcome-bar"><div><span>Registrar resultado</span><small>1–5 resultados · P pular · Espaço pausar · Ctrl+Z desfazer · O objeções</small></div><div class="v987-result-buttons"><button data-v987-result="noanswer"><kbd>1</kbd>Não atendeu</button><button data-v987-result="answered"><kbd>2</kbd>Atendeu</button><button data-v987-result="return"><kbd>3</kbd>Pediu retorno</button><button class="positive" data-v987-result="interested"><kbd>4</kbd>Interessado</button><button class="positive" data-v987-result="meeting"><kbd>5</kbd>Marcou reunião</button><button data-v987-skip>Pular</button></div></footer>`}
function focusTopHTML(l,list,index,st){const p=phoneInfo(l),single=!!st.session?.single;return `<header class="v987-focus-top"><button type="button" data-v987-back>← ${single&&st.session?.origin?'Voltar à origem':'Sair da ligação em foco'}</button><div class="v987-call-identity"><span>${single?'Ligação avulsa':`Ligação ${index+1} de ${list.length}`}</span><b>${esc(leadName(l))}</b></div><div class="v987-timer-zone"><span id="v987CallTimer">${formatDuration(durationSeconds())}</span><button type="button" data-v987-timer="pause">${paused?'Continuar':'Pausar'}</button><button type="button" data-v987-undo>Desfazer</button><a class="${p.valid?'':'disabled'}" href="${esc(p.href)}">Abrir chamada</a></div></header>`}
function routineHTML(){
  const list=routineList(),st=state(),l=currentLead();if(!l)return landingHTML();const index=Math.max(0,list.findIndex(x=>x.id===l.id)),pb=choosePB(l),block=activeBlock(pb,st),focus=st.focus;
  const classes=['v987-focus-shell'];if(!focus.leftOpen)classes.push('left-closed');if(!focus.rightOpen)classes.push('right-closed');if(focus.distraction)classes.push('distraction');
  return `<div class="${classes.join(' ')}">${focusTopHTML(l,list,index,st)}<div class="v987-focus-grid"><aside class="v987-left-panel">${leadContextHTML(l,list,index)}</aside>${scriptCenterHTML(l,pb,st)}${rightPanelHTML(l,pb,st,block)}</div>${outcomeBarHTML()}${scheduleDialogHTML(st.pendingDialog,l)}</div>`
}

function filterButtons(st){const labels={todos:'Todos',hoje:'Hoje',vencidas:'Vencidas',sem:'Sem tentativa',retornos:'Retornos',garimpo:'Garimpo'},counts=filterCounts();return Object.keys(labels).map(v=>`<button class="${st.filter===v?'active':''}" data-v987-filter="${v}" type="button"><span>${labels[v]}</span><b>${counts[v]||0}</b></button>`).join('')}
function summaryHTML(s){if(!s)return'';return `<section class="v987-summary"><div><span>Rotina concluída</span><h2>Resumo das ligações</h2><p>${esc(s.finishedAtLabel)} · ${s.calls} resultado(s)</p></div><div class="v987-summary-kpis"><b>${s.calls}<small>Ligações</small></b><b>${s.answered}<small>Atendidas</small></b><b>${s.interested}<small>Interessados</small></b><b>${s.meetings||0}<small>Reuniões</small></b><b>${esc(formatDuration(s.averageDuration))}<small>Tempo médio</small></b></div><button type="button" data-v987-close-summary>Fechar</button></section>`}
function singleCompleteHTML(s){if(!s)return'';return `<section class="v987-summary single"><div><span>Ligação concluída</span><h2>${esc(s.leadName)}</h2><p>${esc(s.result)} · ${esc(formatDuration(s.duration))}</p></div><div><button type="button" class="primary" data-v987-return-origin>${s.origin?.view==='pipeline'?'Voltar ao Pipeline':'Voltar à origem'}</button><button type="button" data-v987-call-again="${esc(s.leadId)}">Ligar novamente</button><button type="button" data-v987-close-single>Fechar</button></div></section>`}
function landingHTML(){const list=queue(),st=state(),sel=list.find(l=>l.id===st.selectedId)||list[0],metrics=callMetrics(),p=sel?phoneInfo(sel):null;return `<div class="v987-call-home">${singleCompleteHTML(st.singleComplete)}${summaryHTML(st.summary)}<header class="v987-home-hero"><div><span>Central de ligações</span><h1>Prepare a fila e entre no modo Ligação em foco</h1><p>O script fica no centro, com contexto do lead à esquerda e objeções, anotações e histórico à direita.</p></div><div><button class="primary" type="button" data-v987-start ${list.length?'':'disabled'}>${list.length?'Começar ligações':'Fila vazia'}</button><button type="button" data-view="playbooks">Editar Playbooks</button></div></header><div class="v987-home-kpis"><div><span>Na fila</span><b>${list.length}</b></div><div><span>Vencidas</span><b>${queue('vencidas').length}</b></div><div><span>Retornos</span><b>${queue('retornos').length}</b></div><div><span>Ligações registradas</span><b>${metrics.total}</b></div><div><span>Tempo médio</span><b>${esc(formatDuration(metrics.average))}</b></div></div><div class="v987-home-toolbar"><input id="v987CallSearch" placeholder="Buscar lead, cidade, telefone, origem ou campanha..." value="${esc(st.search)}"><div>${filterButtons(st)}</div></div><div class="v987-home-grid"><section class="v987-home-panel"><div class="v987-panel-head"><div><h2>Fila ordenada</h2><p>Prioridade, vencimento, retorno solicitado e valor potencial.</p></div><span>${list.length} leads</span></div><div class="v987-home-queue">${list.map((l,i)=>queueCard(l,i,sel?.id===l.id)).join('')||'<div class="v987-empty">Nenhum lead disponível.</div>'}</div></section><section class="v987-home-panel v987-preview">${sel?leadPreviewHTML(sel)+`<div class="v987-preview-actions"><button class="primary" data-v987-open-call="${esc(sel.id)}" ${p.valid?'':'disabled'}>${p.valid?'Abrir Ligação em foco':'Telefone inválido'}</button></div>`:'<div class="v987-empty">Selecione um lead.</div>'}</section></div></div>`}

function scheduleSuggestion(result){const key={'Não atendeu':'noanswer','Pediu retorno':'return','Marcou reunião':'meeting'}[result],stage=window.CRMOutcomeRules?.followStageFor?.(key);let when={date:today(),time:'10:00'};try{if(stage&&window.CRMV982Followups?.scheduleForStage)when=window.CRMV982Followups.scheduleForStage(stage)}catch(e){}return {stage,date:when.date||today(),time:when.time||stage?.time||'10:00'}}
function scheduleDialogHTML(dialog,l){if(!dialog)return'';const meeting=dialog.result==='Marcou reunião',s=scheduleSuggestion(dialog.result);return `<div class="v987-dialog-backdrop" data-v987-close-dialog><section class="v987-dialog" role="dialog" aria-modal="true"><div class="v987-dialog-head"><div><span>${meeting?'Agenda integrada':'Próximo contato'}</span><h2>${esc(dialog.result)}</h2><p>${meeting?'Defina data e horário para criar a reunião na Agenda.':'Confirme ou ajuste quando o lead deve voltar para a fila.'}</p></div><button type="button" data-v987-close-dialog>×</button></div><div class="v987-dialog-grid"><label>Data<input id="v987ScheduleDate" type="date" value="${esc(dialog.date||s.date)}"></label><label>Horário<input id="v987ScheduleTime" type="time" value="${esc(dialog.time||s.time)}"></label>${meeting?`<label>Duração<select id="v987MeetingDuration"><option value="15">15 minutos</option><option value="30" selected>30 minutos</option><option value="45">45 minutos</option><option value="60">1 hora</option></select></label><label class="wide">Título<input id="v987MeetingTitle" value="Reunião com ${esc(leadName(l))}"></label>`:''}<label class="wide">Próxima ação<input id="v987ScheduleAction" value="${esc(meeting?'Preparar a reunião e confirmar presença':s.stage?.action||'Retomar contato')}"></label></div><div class="v987-dialog-actions"><button type="button" data-v987-close-dialog>Cancelar</button><button class="primary" type="button" data-v987-confirm-result="${esc(dialog.result)}">Confirmar e registrar</button></div></section></div>`}

function start(id,options={}){stopTimer();const filtered=queue(),all=baseQueue(),lead=(id&&all.find(l=>l.id===id))||filtered[0]||all[0];if(!lead)return notify('Nenhum lead disponível para ligação.','warn');const p=phoneInfo(lead);if(!p.valid)return notify(p.reason,'warn');let list=options.single?[lead]:filtered.slice();if(!list.some(l=>l.id===lead.id))list=[lead,...list];if(id&&!options.single)list=[lead,...list.filter(l=>l.id!==lead.id)];const pb=choosePB(lead),st=state();st.routine=true;st.currentId=lead.id;st.selectedId=lead.id;st.processed=[];st.summary=null;st.singleComplete=null;st.pendingDialog=null;st.focus.activeBlockId=blocks(pb)[0]?.id||'';st.focus.editor=false;st.session={id:'call_'+Date.now().toString(36),startedAt:new Date().toISOString(),filter:st.filter,search:st.search,queueIds:list.map(l=>l.id),entries:[],skipped:[],responses:{},objections:[],timerElapsed:0,timerPaused:false,single:!!options.single,origin:options.origin||null};saveState(st);render()}
function activateAndStart(id,options,attempt=0){if($('#ligacoes.active')){start(id,{single:true,...options});return Promise.resolve(true)}try{window.setView?.('ligacoes')}catch(e){}if(attempt>120)return Promise.reject(new Error('A aba Ligações não ficou pronta.'));return new Promise((resolve,reject)=>requestAnimationFrame(()=>activateAndStart(id,options,attempt+1).then(resolve,reject)))}
function openLead(id,options={}){const lead=baseQueue().find(l=>l.id===id);if(!lead)return Promise.reject(new Error('Lead encerrado ou não encontrado.'));const p=phoneInfo(lead);if(!p.valid){notify(p.reason,'warn');return Promise.reject(new Error(p.reason))}return activateAndStart(id,options)}
function saveUndo(data){writeJSON(UNDO_KEY,Object.assign({createdAt:new Date().toISOString()},data))}
function finishRoutine(){const st=state(),entries=st.session?.entries||[],total=entries.reduce((s,e)=>s+Number(e.duration||0),0);st.summary={calls:entries.length,answered:entries.filter(e=>e.result!=='Não atendeu').length,interested:entries.filter(e=>e.result==='Interessado').length,meetings:entries.filter(e=>e.result==='Marcou reunião').length,totalDuration:total,averageDuration:entries.length?Math.round(total/entries.length):0,finishedAtLabel:new Date().toLocaleString('pt-BR')};st.routine=false;st.currentId=null;st.processed=[];st.session=null;st.pendingDialog=null;saveState(st);render();notify('Rotina concluída. O resumo foi gerado.')}
function finishSingle(entry,session){const st=state();st.singleComplete={leadId:entry.leadId,leadName:entry.lead,result:entry.result,duration:entry.duration,origin:session?.origin||null};st.routine=false;st.currentId=null;st.processed=[];st.session=null;st.pendingDialog=null;saveState(st);render();notify('Ligação avulsa registrada.')}
function goNext(){stopTimer();const st=state(),list=routineList(),next=list.find(l=>!(st.processed||[]).includes(l.id));if(!next){finishRoutine();return}st.currentId=next.id;st.selectedId=next.id;st.pendingDialog=null;st.focus.activeBlockId=blocks(choosePB(next))[0]?.id||'';saveState(st);render()}
function skipCurrent(){const st=state(),l=currentLead();if(!l)return;st.processed=Array.from(new Set([...(st.processed||[]),l.id]));st.session.skipped=Array.from(new Set([...(st.session?.skipped||[]),l.id]));saveState(st);if(st.session?.single)return returnToOrigin(st.session.origin);goNext()}
function register(result,options={}){if(registering)return;registering=true;try{const stateBefore=clone(state()),st=state(),list=getLeads(),idx=list.findIndex(l=>l.id===st.currentId),lead=list[idx];if(!lead)return;const leadBefore=clone(lead),seconds=durationSeconds(),now=new Date(),ws=workspace(lead),note=[ws.notes?.summary,ws.notes?.general].filter(Boolean).join(' | ');lead.contatos++;lead.ligacoes++;lead.ultimoResultado=result;lead.tempoLigacoesSegundos+=seconds;lead.ultimaDuracaoLigacao=seconds;lead.historico=Array.isArray(lead.historico)?lead.historico:[];const outcome=window.CRMOutcomeRules?.apply?.({lead,result,schedule:options.schedule||{},meeting:options.meeting||null,source:'Ligação'})||{};const eventId='call_'+Date.now().toString(36);lead.historico.push({id:eventId,tipo:'Ligação',resultado:result,data:today(),hora:nowTime(),duracaoSegundos:seconds,duracaoFormatada:formatDuration(seconds),iniciadoEm:new Date(now.getTime()-seconds*1000).toISOString(),finalizadoEm:now.toISOString(),agendaEventId:outcome.agendaEvent?.id||'',obs:note,respostas:clone(ws.answers||{}),objecoes:clone(st.session?.objections||[])});list[idx]=lead;saveUndo({leadId:lead.id,leadBefore,stateBefore,agendaEventId:outcome.agendaEvent?.id||'',callEventId:eventId});saveLeads(list);try{const key=window.CRMOutcomeRules?.outcomes?.[result]?.key||'';window.CRMEventHub?.emit?.('crm:call-result-recorded',{leadId:lead.id,lead:clone(lead),result,duration:seconds,outcomeKey:key});if(result==='Não atendeu')window.CRMEventHub?.emit?.('crm:call-no-answer',{leadId:lead.id,lead:clone(lead)});else if(result==='Pediu retorno')window.CRMEventHub?.emit?.('crm:call-callback',{leadId:lead.id,lead:clone(lead)});else window.CRMEventHub?.emit?.('crm:call-answered',{leadId:lead.id,lead:clone(lead),result});}catch(e){}st.processed=Array.from(new Set([...(st.processed||[]),lead.id]));const entry={leadId:lead.id,lead:leadName(lead),result,duration:seconds,at:now.toISOString(),agendaEventId:outcome.agendaEvent?.id||''};st.session.entries.push(entry);st.pendingDialog=null;saveState(st);notify(`Ligação registrada: ${result} · ${formatDuration(seconds)}`);if(st.session.single)finishSingle(entry,st.session);else goNext()}finally{setTimeout(()=>registering=false,180)}}
function undoLast(){const u=readJSON(UNDO_KEY,null);if(!u?.leadBefore)return notify('Nenhuma ligação recente para desfazer.','warn');const list=getLeads(),i=list.findIndex(l=>l.id===u.leadId);if(i>=0)list[i]=u.leadBefore;else list.push(u.leadBefore);if(u.agendaEventId)window.CRMOutcomeRules?.removeAgendaEvent?.(u.agendaEventId);saveLeads(list);saveState(Object.assign(defaultState(),u.stateBefore||{}));localStorage.removeItem(UNDO_KEY);render();notify('Última ligação desfeita.')}
function openScheduleDialog(result){const st=state(),s=scheduleSuggestion(result);st.pendingDialog={result,date:s.date,time:s.time};saveState(st);render()}
function confirmScheduledResult(result){const date=$('#v987ScheduleDate')?.value||today(),time=$('#v987ScheduleTime')?.value||'10:00',action=$('#v987ScheduleAction')?.value||'';if(result==='Marcou reunião')register(result,{schedule:{date,time,action},meeting:{date,time,duration:Number($('#v987MeetingDuration')?.value||30),title:$('#v987MeetingTitle')?.value||('Reunião com '+leadName(currentLead())),notes:workspace(currentLead()).notes?.summary||''}});else register(result,{schedule:{date,time,action}})}
function returnToOrigin(origin){const st=state();st.routine=false;st.currentId=null;st.session=null;st.pendingDialog=null;st.singleComplete=null;saveState(st);stopTimer();if(origin?.view==='pipeline'&&window.CRMV65Pipeline?.restoreContext)return window.CRMV65Pipeline.restoreContext(origin.context||{});if(origin?.view)return window.setView?.(origin.view);render()}
function registerObjection(id,status){const l=currentLead(),pb=choosePB(l),o=(pb?.objecoes||[]).find(x=>x.id===id);if(!l||!o)return;const event={id:'obj_'+Date.now().toString(36),objecaoId:o.id,objecao:o.nome,categoria:o.categoria,status,data:today(),hora:nowTime(),bloco:activeBlock(pb,state())?.title||'',resposta:o.resposta};patchLead(l.id,lead=>{lead.objecoesHistorico=Array.isArray(lead.objecoesHistorico)?lead.objecoesHistorico:[];lead.objecoesHistorico.push(event);lead.historico.push({tipo:'Objeção',resultado:`${o.nome} · ${status}`,data:event.data,hora:event.hora,obs:o.resposta})},'ligacoes-objection');const st=state();st.session.objections=st.session.objections||[];st.session.objections.push(event);saveState(st);notify(`Objeção registrada: ${o.nome} — ${status}`);render()}

function render(){const el=$('#ligacoes');if(!el)return;const active=el.classList.contains('active'),st=state();el.className='view grid-view v987-ligacoes-view'+(active?' active':'');el.dataset.renderOwner='ligacoes-v99';el.innerHTML=st.routine?routineHTML():landingHTML();bindRoot(el);if(st.routine){if(!timer&&!startedAt&&!paused){if(!restoreTimer(st))startTimer(true)}else updateTimer()}else stopTimer();updateTopbar();try{document.dispatchEvent(new CustomEvent('crm:layout-refresh',{detail:{view:'ligacoes'}}))}catch(e){}}
function updateTopbar(){if(!$('#ligacoes.active'))return;const t=$('#topbarTitle'),s=$('#topbarSub');if(t)t.textContent=state().routine?'Ligação em foco':'Ligações';if(s)s.textContent=state().routine?'Script central, contexto do lead e assistência comercial':'Fila priorizada e rotina de ligações'}
function ensureOwner(){const el=$('#ligacoes');if(!el||!el.classList.contains('active'))return;if(el.dataset.renderOwner!=='ligacoes-v99'||(!el.querySelector('.v987-focus-shell')&&!el.querySelector('.v987-call-home')))render()}
function bindRoot(el){if(el._v987Bound)return;el._v987Bound=true;
  el.addEventListener('input',e=>{
    if(e.target.id==='v987CallSearch'){const st=state();st.search=e.target.value;st.selectedId=null;saveState(st);clearTimeout(el._search);el._search=setTimeout(render,180);return}
    if(e.target.matches('[data-v987-note]')){saveWorkspaceField(currentLead()?.id,'note',e.target.dataset.v987Note,e.target.value);return}
    if(e.target.matches('[data-v987-block-note]')){saveWorkspaceField(currentLead()?.id,'blockNote',e.target.dataset.v987BlockNote,e.target.value);return}
    if(e.target.matches('[data-v987-objection-search]')){const st=state();st.focus.objectSearch=e.target.value;saveState(st);clearTimeout(el._objSearch);el._objSearch=setTimeout(render,180);return}
  });
  el.addEventListener('change',e=>{
    const multi=e.target.closest('[data-v987-multi-answer]');if(multi){const blockId=multi.dataset.v987MultiAnswer,pb=choosePB(currentLead()),block=blocks(pb).find(b=>b.id===blockId),values=$$(`[data-v987-multi-answer="${CSS.escape(blockId)}"]:checked`,el).map(x=>x.value);saveAnswer(block,values,values.join(', '));return}
    if(e.target.matches('[data-v987-note]'))saveWorkspaceField(currentLead()?.id,'note',e.target.dataset.v987Note,e.target.value);
  });
  el.addEventListener('click',e=>{
    const filter=e.target.closest('[data-v987-filter]');if(filter){const st=state();st.filter=filter.dataset.v987Filter;st.selectedId=null;saveState(st);render();return}
    const select=e.target.closest('[data-v987-select]');if(select){const st=state();st.selectedId=select.dataset.v987Select;if(st.routine){stopTimer();st.currentId=select.dataset.v987Select;st.focus.activeBlockId=blocks(choosePB(getLeads().find(l=>l.id===st.currentId)))[0]?.id||''}saveState(st);render();return}
    const startBtn=e.target.closest('[data-v987-start]');if(startBtn&&!startBtn.disabled){start(startBtn.dataset.v987Start||state().selectedId);return}
    const direct=e.target.closest('[data-v987-open-call]');if(direct&&!direct.disabled){openLead(direct.dataset.v987OpenCall).catch(()=>{});return}
    if(e.target.closest('[data-v987-back]')){const st=state();if(st.session?.single&&st.session.origin)returnToOrigin(st.session.origin);else{st.routine=false;st.currentId=null;st.session=null;st.processed=[];st.pendingDialog=null;saveState(st);render()}return}
    if(e.target.closest('[data-v987-toggle-left]')){const st=state();st.focus.leftOpen=!st.focus.leftOpen;saveState(st);render();return}
    if(e.target.closest('[data-v987-toggle-right]')){const st=state();st.focus.rightOpen=!st.focus.rightOpen;saveState(st);render();return}
    if(e.target.closest('[data-v987-distraction]')){const st=state();st.focus.distraction=!st.focus.distraction;if(st.focus.distraction){st.focus.leftOpen=false;st.focus.rightOpen=false}else{st.focus.leftOpen=true;st.focus.rightOpen=true}saveState(st);render();return}
    const tab=e.target.closest('[data-v987-right-tab]');if(tab){const st=state();st.focus.rightTab=tab.dataset.v987RightTab;saveState(st);render();return}
    const cat=e.target.closest('[data-v987-objection-category]');if(cat){const st=state();st.focus.objectCategory=cat.dataset.v987ObjectionCategory;saveState(st);render();return}
    const block=e.target.closest('[data-v987-block]');if(block){setActiveBlock(block.dataset.v987Block);return}
    if(e.target.closest('[data-v987-prev]')){adjacentBlock('prev');return}if(e.target.closest('[data-v987-next]')){adjacentBlock('next');return}
    const answer=e.target.closest('[data-v987-answer]');if(answer){const pb=choosePB(currentLead()),b=blocks(pb).find(x=>x.id===answer.dataset.v987Answer),o=b?.options?.find(x=>x.id===answer.dataset.optionId);if(b&&o)goFromOption(b,o);return}
    const copyBlock=e.target.closest('[data-v987-copy-block]');if(copyBlock){const pb=choosePB(currentLead()),b=blocks(pb).find(x=>x.id===copyBlock.dataset.v987CopyBlock);copyText(fill(b?.content,currentLead()));notify('Trecho copiado.');return}
    const copyObj=e.target.closest('[data-v987-copy-objection]');if(copyObj){const o=(choosePB(currentLead())?.objecoes||[]).find(x=>x.id===copyObj.dataset.v987CopyObjection);copyText(o?.resposta||'');notify('Resposta copiada.');return}
    const regObj=e.target.closest('[data-v987-register-objection]');if(regObj){registerObjection(regObj.dataset.v987RegisterObjection,regObj.dataset.status);return}
    if(e.target.closest('[data-v987-open-studio]')){pauseAndPersist();window.CRMPlaybookStudio?.open?.(choosePB(currentLead())?.id,{returnToCall:true})||window.setView?.('playbooks');return}
    if(e.target.closest('[data-v987-open-lead]')){window.CRMV94Official?.openLeadDrawer?.(e.target.closest('[data-v987-open-lead]').dataset.v987OpenLead);return}
    if(e.target.closest('[data-v987-timer="pause"]')){toggleTimer();return}
    if(e.target.closest('[data-v987-undo]')){undoLast();return}
    if(e.target.closest('[data-v987-skip]')){skipCurrent();return}
    const result=e.target.closest('[data-v987-result]');if(result){const map={noanswer:'Não atendeu',answered:'Atendeu',return:'Pediu retorno',interested:'Interessado',meeting:'Marcou reunião'},v=map[result.dataset.v987Result];if(['Não atendeu','Pediu retorno','Marcou reunião'].includes(v))openScheduleDialog(v);else register(v);return}
    if(e.target.closest('[data-v987-close-dialog]')){const st=state();st.pendingDialog=null;saveState(st);render();return}
    const conf=e.target.closest('[data-v987-confirm-result]');if(conf){confirmScheduledResult(conf.dataset.v987ConfirmResult);return}
    if(e.target.closest('[data-v987-close-summary]')){const st=state();st.summary=null;saveState(st);render();return}
    if(e.target.closest('[data-v987-return-origin]')){returnToOrigin(state().singleComplete?.origin);return}
    const again=e.target.closest('[data-v987-call-again]');if(again){openLead(again.dataset.v987CallAgain,{origin:state().singleComplete?.origin}).catch(()=>{});return}
    if(e.target.closest('[data-v987-close-single]')){const st=state();st.singleComplete=null;saveState(st);render();return}
  });
}
function handleKeyboard(e){if(e.defaultPrevented)return;if((e.ctrlKey||e.metaKey)&&norm(e.key)==='z'){if($('#ligacoes.active')){e.preventDefault();undoLast()}return}if(e.ctrlKey||e.metaKey||e.altKey)return;const tag=e.target?.tagName?.toLowerCase();if(['input','textarea','select'].includes(tag)||e.target?.isContentEditable)return;if(!$('#ligacoes.active')||!state().routine)return;const map={'1':'Não atendeu','2':'Atendeu','3':'Pediu retorno','4':'Interessado','5':'Marcou reunião'};if(map[e.key]){e.preventDefault();if(['Não atendeu','Pediu retorno','Marcou reunião'].includes(map[e.key]))openScheduleDialog(map[e.key]);else register(map[e.key]);return}if(norm(e.key)==='p'){e.preventDefault();skipCurrent();return}if(norm(e.key)==='o'){e.preventDefault();const st=state();st.focus.rightOpen=true;st.focus.rightTab='objections';saveState(st);render();return}if(e.key==='ArrowRight'){e.preventDefault();adjacentBlock('next');return}if(e.key==='ArrowLeft'){e.preventDefault();adjacentBlock('prev');return}if(e.code==='Space'){e.preventDefault();toggleTimer()}}

const api={version:VERSION,render,start,openLead,state,queue,filterCounts,register,finishRoutine,formatDuration,undoLast,phoneInfo};
window.CRMV990Ligacoes=api;window.CRMV987Ligacoes=api;window.CRMV984Ligacoes=api;window.CRMV982Ligacoes=api;
document.addEventListener('crm:datachange',()=>{if($('#ligacoes.active')&&!state().routine)render()});
document.addEventListener('keydown',handleKeyboard,true);
document.addEventListener('click',e=>{const btn=e.target.closest('[data-v985-call-lead],[data-call-lead]');if(!btn||btn.disabled)return;e.preventDefault();openLead(btn.getAttribute('data-v985-call-lead')||btn.getAttribute('data-call-lead')).catch(()=>{})},true);
document.addEventListener('crm:call-lead-request',e=>openLead(e.detail?.id,e.detail?.options||{}).catch(()=>{}));
const root=$('#ligacoes');if(root&&!root._v987OwnerObserver){root._v987OwnerObserver=new MutationObserver(()=>{clearTimeout(ownerTimer);ownerTimer=setTimeout(ensureOwner,45)});root._v987OwnerObserver.observe(root,{childList:true,attributes:true,attributeFilter:['class','data-render-owner']})}
try{document.dispatchEvent(new CustomEvent('crm:calls-ready',{detail:{api}}))}catch(e){}
})();
