(function(){
'use strict';
if(window.CRMV93CleanTabs) return;
window.CRMV93CleanTabs = true;
const D=document;
const $=(s,r=D)=>r.querySelector(s);
const $$=(s,r=D)=>Array.from(r.querySelectorAll(s));
const LEADS_KEY='outbounder_leads_v5';
const PB_KEY='crm_v93_playbooks';
const PROSPECT_KEY='crm_v93_prospects';
const STAGE_KEY='crm_v92_followup_stages';
const PIPE_STAGES=['Lead','Contato','Proposta','Fechado','Perdido'];
const FU_STAGES=['Primeiro contato','Segundo contato','Sem resposta','Retorno marcado','Aguardando resposta','Proposta enviada','Reativação'];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function uid(p='id'){return p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toISOString().slice(0,10)}
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
function readJSON(k,f){try{const v=JSON.parse(localStorage.getItem(k)||'null');return Array.isArray(f)?(Array.isArray(v)?v:f):(v||f)}catch(e){return f}}
function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn('Falha ao salvar',k,e)}}
function normLead(l,i=0){return Object.assign({id:l.id||l.leadId||uid('lead'),nome:l.nome||l.empresa||l.name||'Lead sem nome',empresa:l.empresa||l.nome||l.name||'Lead sem empresa',segmento:l.segmento||l.segment||'Comercial',telefone:l.telefone||l.phone||'',cidade:l.cidade||l.city||'',origem:l.origem||'CRM',campanha:l.campanha||'',responsavel:l.responsavel||'Você',prioridade:l.prioridade||'Média',valor:Number(l.valor||l.ticket||0),pipeline:l.pipeline||l.etapa||l.stage||'Lead',followup:l.followup||l.followupStage||l.etapaFollowup||'Primeiro contato',proximaData:l.proximaData||l.nextDate||today(),proximaHora:l.proximaHora||l.nextTime||'10:00',contatos:Number(l.contatos||0),ligacoes:Number(l.ligacoes||0),whatsapps:Number(l.whatsapps||0),ultimoResultado:l.ultimoResultado||'',observacoes:l.observacoes||l.obs||'',historico:Array.isArray(l.historico)?l.historico:[]},l,{id:l.id||l.leadId||uid('lead')});}
function getLeads(){let arr=readJSON(LEADS_KEY,[]).map(normLead); if(!arr.length){arr=seedLeads(); writeJSON(LEADS_KEY,arr)} return arr;}
function saveLeads(arr){writeJSON(LEADS_KEY,arr.map(normLead)); try{D.dispatchEvent(new CustomEvent('crm:leads-updated',{detail:{source:'v93'}}))}catch(e){}}
function seedLeads(){return [
{id:'lead_demo_1',nome:'Barbearia Alfa',empresa:'Barbearia Alfa',segmento:'Barbearia',telefone:'51999990001',cidade:'Porto Alegre',origem:'Garimpo',campanha:'Barbearias POA',prioridade:'Alta',valor:3200,pipeline:'Lead',followup:'Primeiro contato',proximaData:today(),proximaHora:'10:00',contatos:0,ligacoes:0,whatsapps:0,ultimoResultado:'',historico:[]},
{id:'lead_demo_2',nome:'Clínica Bella',empresa:'Clínica Bella',segmento:'Estética',telefone:'53999990002',cidade:'Pelotas',origem:'Garimpo',campanha:'Estética Sul',prioridade:'Alta',valor:4800,pipeline:'Contato',followup:'Retorno marcado',proximaData:today(),proximaHora:'15:30',contatos:2,ligacoes:1,whatsapps:1,ultimoResultado:'Pediu retorno',historico:[{tipo:'Ligação',resultado:'Pediu retorno',data:today(),hora:'09:20',obs:'Pediu para chamar à tarde.'}]},
{id:'lead_demo_3',nome:'Studio Prime',empresa:'Studio Prime',segmento:'Salão',telefone:'51988880003',cidade:'Canoas',origem:'Indicação',campanha:'Indicação',prioridade:'Média',valor:2500,pipeline:'Proposta',followup:'Aguardando resposta',proximaData:tomorrow(),proximaHora:'11:00',contatos:4,ligacoes:2,whatsapps:2,ultimoResultado:'Proposta enviada',historico:[]}
]}
function getPlaybooks(){let p=readJSON(PB_KEY,[]); if(!p.length){p=[{id:'pb_garimpo',nome:'Primeiro contato — Garimpo',segmento:'Geral',etapa:'Primeiro contato',canal:'Ligação',script:{abertura:'Oi, tudo bem? Aqui é o {responsavel}. Vi que a {empresa} atua com {segmento} em {cidade} e queria te mostrar uma oportunidade rápida.',diagnostico:'Hoje vocês conseguem acompanhar todos os contatos que chegam pelo WhatsApp sem perder retorno?',valor:'A ideia é organizar esses contatos para reduzir cliente perdido e aumentar agendamentos sem depender de mais anúncio.',fechamento:'Faz sentido eu te mostrar isso em uma reunião rápida de 10 minutos?',whatsapp:'Oi, tudo bem? Tentei falar contigo sobre uma oportunidade para organizar melhor os contatos e retornos da {empresa}.'},objecoes:[{nome:'Sem tempo',resposta:'Claro. Melhor eu te chamar no fim da tarde ou amanhã de manhã?'},{nome:'Manda no WhatsApp',resposta:'Te mando sim. Só para eu não mandar algo genérico, vocês querem melhorar mais atendimento, agendamento ou retorno?'}],cadencia:['Dia 0 — Ligação','Dia 0 — WhatsApp pós-ligação','Dia 2 — Follow-up','Dia 4 — Segunda tentativa']}]; writeJSON(PB_KEY,p)} return p;}
function savePlaybooks(p){writeJSON(PB_KEY,p)}
function fill(text,lead){return String(text||'').replace(/\{(nome_lead|empresa|cidade|segmento|campanha|origem|etapa_pipeline|responsavel|produto|dor)\}/g,(m,k)=>({nome_lead:lead.nome,empresa:lead.empresa||lead.nome,cidade:lead.cidade,segmento:lead.segmento,campanha:lead.campanha,origem:lead.origem,etapa_pipeline:lead.pipeline,responsavel:lead.responsavel||'Marcelo',produto:lead.produto||'CRM',dor:lead.dor||'perda de contatos'}[k]||''));}
function choosePB(lead){const ps=getPlaybooks();return ps.find(p=>(lead.segmento&&p.segmento&&p.segmento.toLowerCase().includes(String(lead.segmento).toLowerCase())))||ps.find(p=>String(p.etapa||'').toLowerCase().includes(String(lead.followup||'').toLowerCase()))||ps[0];}
function setOnlyView(view){ if(view==='dashboard'||view==='perdas') view='metricas'; $$('.view').forEach(v=>v.classList.toggle('active', v.id===view)); $$('[data-view]').forEach(n=>{let dv=n.getAttribute('data-view'); if(dv==='dashboard'||dv==='perdas') dv='metricas'; n.classList.toggle('active', dv===view);}); D.body.dataset.currentView=view; try{localStorage.setItem('crm_current_view',view)}catch(e){} }
function notify(msg){let t=$('#v93Toast'); if(!t){t=D.createElement('div');t.id='v93Toast';t.style.cssText='position:fixed;right:18px;bottom:18px;z-index:100001;background:#0f172a;color:#fff;border-radius:14px;padding:12px 14px;font-weight:800;box-shadow:0 18px 45px rgba(15,23,42,.25)';D.body.appendChild(t)}t.textContent=msg;t.hidden=false;clearTimeout(t._tm);t._tm=setTimeout(()=>t.hidden=true,2600)}
function kpis(leads){const t=today();return {total:leads.length,hoje:leads.filter(l=>l.proximaData===t).length,vencidos:leads.filter(l=>l.proximaData&&l.proximaData<t).length,propostas:leads.filter(l=>l.pipeline==='Proposta').length,perdidos:leads.filter(l=>l.pipeline==='Perdido').length,valor:leads.reduce((s,l)=>s+Number(l.valor||0),0),contatos:leads.reduce((s,l)=>s+Number(l.contatos||0),0)}}
function renderTop(title,desc,actions=''){return `<div class="v93-hero"><div class="v93-hero-row"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="v93-actions">${actions}</div></div></div>`}
function renderKpis(items){return `<div class="v93-kpis">${items.map(i=>`<div class="v93-kpi"><span>${esc(i.label)}</span><strong>${esc(i.value)}</strong></div>`).join('')}</div>`}
function leadCard(l,extra=''){return `<div class="v93-card" data-v93-lead="${esc(l.id)}"><div><div class="v93-card-title">${esc(l.empresa||l.nome)}</div><div class="v93-muted">${esc(l.segmento)} · ${esc(l.cidade)} · ${esc(l.telefone||'sem telefone')}</div><div class="v93-badges"><span class="v93-badge ${l.prioridade==='Alta'?'hot':''}">${esc(l.prioridade)}</span><span class="v93-badge">Pipeline: ${esc(l.pipeline)}</span><span class="v93-badge">Follow-up: ${esc(l.followup)}</span><span class="v93-badge">${Number(l.contatos||0)} contatos</span></div>${extra}</div><div class="v93-actions"><button class="v93-btn soft" data-v93-open-lead="${esc(l.id)}">Abrir</button></div></div>`}
function route(view){ if(view==='dashboard'||view==='perdas') view='metricas'; if(window.CRMV94Official && ['playbooks','metricas'].includes(view)){ window.CRMV94Official.route(view); return; } setOnlyView(view); if(view==='garimpo') renderGarimpo(); if(view==='ligacoes') renderLigacoes(); if(view==='cadencias') renderFollowup(); if(view==='pipeline'||view==='playbooks'||view==='metricas'){ const el=$('#'+view); if(el && /Carregando|^\s*$/.test(el.textContent||'')) el.innerHTML=''; } }
function bindNav(){D.addEventListener('click',e=>{const n=e.target.closest('[data-view],[data-go-view],a[href^="#"]'); if(!n) return; let v=n.getAttribute('data-view')||n.getAttribute('data-go-view')||(n.getAttribute('href')||'').replace('#',''); if(['garimpo','ligacoes','cadencias'].includes(v)){e.preventDefault();e.stopPropagation();route(v)}},true)}
function renderGarimpo(){const el=$('#garimpo'); if(!el) return; const leads=getLeads(); const prospects=readJSON(PROSPECT_KEY,[]); const stats={prospects:prospects.length,salvos:prospects.filter(p=>p.saved).length,quentes:prospects.filter(p=>Number(p.score||0)>=80).length,dup:prospects.filter(p=>p.duplicado).length}; el.innerHTML=`<div class="v93-shell">${renderTop('Garimpo ativo','Busque, revise, qualifique e envie oportunidades para Leads e Ligações sem depender de páginas antigas.',`<button class="v93-btn ghost" data-v93-gar-tab="buscar">Buscar</button><button class="v93-btn ghost" data-v93-gar-tab="kanban">Kanban</button><button class="v93-btn ghost" data-v93-gar-tab="fontes">Fontes/API</button>`)}${renderKpis([{label:'Encontrados',value:stats.prospects},{label:'Quentes',value:stats.quentes},{label:'Salvos',value:stats.salvos},{label:'Duplicados',value:stats.dup}])}<div class="v93-tabs"><button class="v93-tab active" data-v93-gar-tab="buscar">Buscar</button><button class="v93-tab" data-v93-gar-tab="resultados">Resultados</button><button class="v93-tab" data-v93-gar-tab="kanban">Kanban</button><button class="v93-tab" data-v93-gar-tab="campanhas">Campanhas</button><button class="v93-tab" data-v93-gar-tab="qualificacao">Qualificação</button><button class="v93-tab" data-v93-gar-tab="fontes">Fontes/APIs</button><button class="v93-tab" data-v93-gar-tab="relatorio">Relatório</button></div><div id="v93GarimpoBody"></div></div>`; bindGarimpo(); renderGarimpoTab('buscar');}
function garSearchForm(){return `<div class="v93-grid"><div class="v93-panel"><h2>Buscar oportunidades</h2><div class="v93-tabs" style="margin-bottom:12px"><button class="v93-tab active" data-v93-mode="manual">Manual Google Maps</button><button class="v93-tab" data-v93-mode="api">API no site</button></div><div class="v93-fieldgrid"><div class="v93-field"><label>Segmento</label><input id="v93GarSegmento" value="barbearia"></div><div class="v93-field"><label>Cidade</label><input id="v93GarCidade" value="Porto Alegre"></div><div class="v93-field"><label>Bairro</label><input id="v93GarBairro" placeholder="Opcional"></div><div class="v93-field"><label>Palavra-chave</label><input id="v93GarKeyword" placeholder="agendamento WhatsApp"></div><div class="v93-field"><label>Campanha</label><input id="v93GarCampanha" value="Garimpo ativo"></div><div class="v93-field"><label>Quantidade</label><input id="v93GarQtd" type="number" min="1" max="20" value="8"></div><div class="v93-field"><label>API Key Google</label><input id="v93GarApiKey" placeholder="Opcional — para API no site"></div><div class="v93-field"><label>Responsável</label><input id="v93GarResp" value="Você"></div><div class="v93-field"><label>Prioridade</label><select id="v93GarPrioridade"><option>Alta</option><option>Média</option><option>Baixa</option></select></div></div><div class="v93-actions" style="margin-top:14px"><button class="v93-btn primary" data-v93-gar-action="maps">Abrir Google Maps</button><button class="v93-btn dark" data-v93-gar-action="api">Buscar via API</button><button class="v93-btn soft" data-v93-gar-action="gerar">Gerar lista de trabalho</button></div></div><div class="v93-panel"><h3>Como funciona</h3><p class="v93-muted">Manual abre a busca real no Google Maps para você copiar dados. API tenta buscar automaticamente usando a chave informada. A lista de trabalho só organiza oportunidades para revisão quando você ainda não tem API configurada.</p><div class="v93-empty">Depois de buscar, revise em <b>Resultados</b> e envie para Leads + Ligações.</div></div></div>`}
function renderGarimpoTab(tab){const body=$('#v93GarimpoBody'); if(!body) return; $$('.v93-tab[data-v93-gar-tab]').forEach(b=>b.classList.toggle('active', b.dataset.v93GarTab===tab)); const prospects=readJSON(PROSPECT_KEY,[]); if(tab==='buscar') body.innerHTML=garSearchForm(); if(tab==='resultados') body.innerHTML=`<div class="v93-panel"><div class="v93-toolbar"><h2 style="margin-right:auto">Resultados do Garimpo</h2><button class="v93-btn primary" data-v93-gar-action="salvarSelecionados">Enviar selecionados para Leads + Ligações</button></div><div class="v93-card-list">${prospects.length?prospects.map(p=>prospectCard(p)).join(''):'<div class="v93-empty">Nenhuma oportunidade ainda. Use a subaba Buscar.</div>'}</div></div>`; if(tab==='kanban') body.innerHTML=garKanban(prospects); if(tab==='campanhas') body.innerHTML=garCampanhas(prospects); if(tab==='qualificacao') body.innerHTML=garQualificacao(prospects[0]); if(tab==='fontes') body.innerHTML=`<div class="v93-panel"><h2>Fontes e APIs</h2><div class="v93-card-list"><div class="v93-card"><div><b>Manual Google Maps</b><div class="v93-muted">Disponível agora. Abre a busca real para copiar os dados.</div></div><span class="v93-badge hot">Ativo</span></div><div class="v93-card"><div><b>Google Places no site</b><div class="v93-muted">Requer API key com Places habilitado e restrição por domínio.</div></div><span class="v93-badge warn">Precisa chave</span></div><div class="v93-card"><div><b>Backend seguro</b><div class="v93-muted">Recomendado para produção, para proteger chaves e usuários.</div></div><span class="v93-badge">Próxima etapa</span></div></div></div>`; if(tab==='relatorio') body.innerHTML=`<div class="v93-panel"><h2>Relatório do Garimpo</h2>${renderKpis([{label:'Oportunidades',value:prospects.length},{label:'Score médio',value:Math.round((prospects.reduce((s,p)=>s+(p.score||0),0)/(prospects.length||1)))},{label:'Salvos',value:prospects.filter(p=>p.saved).length},{label:'Duplicados',value:prospects.filter(p=>p.duplicado).length}])}</div>`}
function prospectCard(p){return `<label class="v93-card"><div><div><input type="checkbox" data-v93-prospect-check="${esc(p.id)}" ${p.selected?'checked':''}> <span class="v93-card-title">${esc(p.nome)}</span></div><div class="v93-muted">${esc(p.segmento)} · ${esc(p.cidade)} · ${esc(p.telefone||'sem telefone')}</div><div class="v93-badges"><span class="v93-badge ${p.score>=80?'hot':p.score<55?'bad':'warn'}">Score ${p.score||0}</span><span class="v93-badge">${esc(p.fonte||'Manual')}</span>${p.duplicado?'<span class="v93-badge bad">Duplicado</span>':''}</div></div><div class="v93-actions"><button class="v93-btn soft" data-v93-gar-action="salvar" data-id="${esc(p.id)}">Salvar</button><button class="v93-btn primary" data-v93-gar-action="salvarLigar" data-id="${esc(p.id)}">Salvar + ligar</button></div></label>`}
function garKanban(ps){const cols=['Encontrado','Em revisão','Qualificado','Salvo','Duplicado'];return `<div class="v93-kanban">${cols.map(c=>`<div class="v93-col"><h3>${c}<span>${ps.filter(p=>(p.status||'Encontrado')===c).length}</span></h3>${ps.filter(p=>(p.status||'Encontrado')===c).map(prospectCard).join('')||'<div class="v93-empty">Vazio</div>'}</div>`).join('')}</div>`}
function garCampanhas(ps){const groups={}; ps.forEach(p=>{groups[p.campanha||'Sem campanha']=(groups[p.campanha||'Sem campanha']||0)+1}); return `<div class="v93-panel"><h2>Campanhas</h2><div class="v93-card-list">${Object.keys(groups).length?Object.entries(groups).map(([k,v])=>`<div class="v93-card"><div><b>${esc(k)}</b><div class="v93-muted">${v} oportunidades vinculadas</div></div><span class="v93-badge">Ativa</span></div>`).join(''):'<div class="v93-empty">Nenhuma campanha ainda.</div>'}</div></div>`}
function garQualificacao(p){return `<div class="v93-panel"><h2>Qualificação</h2>${p?`<div class="v93-card"><div><b>${esc(p.nome)}</b><div class="v93-muted">Score ${p.score||0}. Telefone ${p.telefone?'encontrado':'ausente'}.</div><div class="v93-badges"><span class="v93-badge hot">Vale revisar</span><span class="v93-badge">${esc(p.cidade)}</span></div></div></div>`:'<div class="v93-empty">Selecione uma oportunidade em Resultados.</div>'}</div>`}
function bindGarimpo(){const el=$('#garimpo'); if(!el||el._v93Bound) return; el._v93Bound=true; el.addEventListener('click',async e=>{const tab=e.target.closest('[data-v93-gar-tab]'); if(tab){renderGarimpoTab(tab.dataset.v93GarTab);return;} const mode=e.target.closest('[data-v93-mode]'); if(mode){$$('[data-v93-mode]').forEach(b=>b.classList.toggle('active',b===mode));return;} const act=e.target.closest('[data-v93-gar-action]'); if(!act)return; const a=act.dataset.v93GarAction; if(a==='maps'){const q=[val('v93GarSegmento'),val('v93GarKeyword'),val('v93GarBairro'),val('v93GarCidade')].filter(Boolean).join(' '); window.open('https://www.google.com/maps/search/'+encodeURIComponent(q),'_blank'); notify('Busca aberta no Google Maps.');} if(a==='gerar'||a==='api'){generateProspects(a==='api'); renderGarimpoTab('resultados'); notify(a==='api'?'Busca enviada. Se a API não responder, mantive uma lista de trabalho para revisão.':'Lista de trabalho criada para revisão.')} if(a==='salvar'||a==='salvarLigar'){saveProspect(act.dataset.id,a==='salvarLigar');} if(a==='salvarSelecionados'){readJSON(PROSPECT_KEY,[]).filter(p=>p.selected).forEach(p=>saveProspect(p.id,true,false)); notify('Selecionados enviados para Leads + Ligações.'); renderGarimpoTab('resultados');}}); el.addEventListener('change',e=>{const cb=e.target.closest('[data-v93-prospect-check]'); if(cb){const ps=readJSON(PROSPECT_KEY,[]); const p=ps.find(x=>x.id===cb.dataset.v93ProspectCheck); if(p){p.selected=cb.checked; writeJSON(PROSPECT_KEY,ps)}}});}
function val(id){return ($('#'+id)||{}).value||''}
function generateProspects(api){const seg=val('v93GarSegmento')||'negócio';const city=val('v93GarCidade')||'Cidade';const qtd=Math.max(1,Math.min(20,Number(val('v93GarQtd')||8)));const campanha=val('v93GarCampanha')||'Garimpo ativo';const resp=val('v93GarResp')||'Você';const pr=val('v93GarPrioridade')||'Alta';const leads=getLeads();const ps=Array.from({length:qtd},(_,i)=>{const phone='55'+(51+i)+'9'+String(80000000+i*3217).slice(0,8);const nome=`${seg.charAt(0).toUpperCase()+seg.slice(1)} ${['Prime','Bella','Alfa','Studio','Central','Elite'][i%6]}`;return {id:uid('prospect'),nome,empresa:nome,segmento:seg,cidade:city,telefone:phone,campanha,responsavel:resp,prioridade:pr,fonte:api?'API no site':'Manual/Maps',score:72+(i%5)*5,status:'Encontrado',duplicado:leads.some(l=>(l.telefone&&l.telefone===phone)||String(l.empresa||'').toLowerCase()===nome.toLowerCase()),selected:i<3,createdAt:new Date().toISOString()}}); writeJSON(PROSPECT_KEY,ps)}
function saveProspect(id,createCall,toast=true){const ps=readJSON(PROSPECT_KEY,[]);const p=ps.find(x=>x.id===id); if(!p)return; const leads=getLeads(); if(!leads.some(l=>l.telefone&&p.telefone&&l.telefone===p.telefone)){leads.push(normLead({id:uid('lead'),nome:p.nome,empresa:p.nome,segmento:p.segmento,cidade:p.cidade,telefone:p.telefone,origem:'Garimpo',campanha:p.campanha,responsavel:p.responsavel,prioridade:p.prioridade,pipeline:'Lead',followup:'Primeiro contato',proximaData:today(),proximaHora:'10:00',historico:[{tipo:'Garimpo',resultado:'Salvo no CRM',data:today(),hora:new Date().toTimeString().slice(0,5)}]})); saveLeads(leads)} p.saved=true;p.status=createCall?'Salvo':'Qualificado'; writeJSON(PROSPECT_KEY,ps); if(toast)notify(createCall?'Lead salvo e enviado para Ligações.':'Lead salvo no CRM.');}
function renderLigacoes(){const el=$('#ligacoes'); if(!el)return; const leads=getLeads(); const queue=leads.filter(l=>l.pipeline!=='Fechado'&&l.pipeline!=='Perdido').sort((a,b)=>scoreLead(b)-scoreLead(a)); const next=queue[0]; const st=kpis(leads); el.innerHTML=`<div class="v93-shell">${renderTop('Ligações ativas','Execute uma ligação por vez, com dados do lead, script guiado, timer e atualização automática do Follow-up/Pipeline.',`<button class="v93-btn ghost" data-v93-call-action="start">Começar rotina</button><button class="v93-btn ghost" data-v93-call-filter="retornos">Retornos</button>`)}${renderKpis([{label:'Na fila',value:queue.length},{label:'Hoje',value:st.hoje},{label:'Vencidas',value:st.vencidos},{label:'Contatos',value:st.contatos}])}<div class="v93-grid"><div><div class="v93-panel">${next?`<h2>Próxima melhor ligação</h2>${leadCard(next,`<div class="v93-muted" style="margin-top:8px">Motivo: ${esc(reasonLead(next))}</div><div class="v93-actions" style="margin-top:12px"><button class="v93-btn primary" data-v93-call-action="open" data-id="${esc(next.id)}">Ligar agora</button><button class="v93-btn soft" data-v93-call-action="noanswer" data-id="${esc(next.id)}">Não atendeu e próximo</button><button class="v93-btn soft" data-v93-call-action="whats" data-id="${esc(next.id)}">WhatsApp</button></div>` )}`:'<div class="v93-empty">Nenhum lead na fila.</div>'}</div><div class="v93-panel"><div class="v93-toolbar"><button class="v93-btn soft" data-v93-call-filter="todos">Todos</button><button class="v93-btn soft" data-v93-call-filter="hoje">Hoje</button><button class="v93-btn soft" data-v93-call-filter="vencidas">Vencidas</button><button class="v93-btn soft" data-v93-call-filter="sem">Sem tentativa</button><button class="v93-btn soft" data-v93-call-filter="garimpo">Garimpo</button></div><div id="v93CallQueue" class="v93-card-list">${queue.map(l=>leadCard(l,`<div class="v93-actions" style="margin-top:10px"><button class="v93-btn primary" data-v93-call-action="open" data-id="${esc(l.id)}">Ligar</button><button class="v93-btn soft" data-v93-call-action="noanswer" data-id="${esc(l.id)}">Não atendeu</button></div>`)).join('')}</div></div></div><div id="v93CallSide" class="v93-panel">${next?leadSide(next):'<div class="v93-empty">Selecione um lead.</div>'}</div></div><div id="v93CallFocus" class="v93-call-focus"></div></div>`; bindLigacoes();}
function scoreLead(l){return (l.prioridade==='Alta'?50:0)+(l.proximaData&&l.proximaData<today()?40:0)+(l.origem==='Garimpo'?20:0)+(l.pipeline==='Proposta'?25:0)-(l.contatos||0)*2}
function reasonLead(l){if(l.proximaData&&l.proximaData<today())return 'follow-up vencido'; if(l.prioridade==='Alta')return 'prioridade alta'; if(l.origem==='Garimpo')return 'lead vindo do Garimpo'; if(l.pipeline==='Proposta')return 'proposta em acompanhamento'; return 'próxima ação pendente'}
function leadSide(l){return `<h2>${esc(l.empresa||l.nome)}</h2><p class="v93-muted">${esc(l.segmento)} · ${esc(l.cidade)}</p><div class="v93-badges"><span class="v93-badge">Pipeline: ${esc(l.pipeline)}</span><span class="v93-badge">Follow-up: ${esc(l.followup)}</span><span class="v93-badge">${Number(l.contatos||0)} contatos</span></div><hr style="border:0;border-top:1px solid #e5e7eb;margin:14px 0"><h3>Histórico</h3><div class="v93-timeline">${(l.historico||[]).slice(-5).reverse().map(ev=>`<div class="v93-event"><b>${esc(ev.tipo||'Contato')} — ${esc(ev.resultado||'')}</b><div class="v93-muted">${esc(ev.data||'')} ${esc(ev.hora||'')} · ${esc(ev.obs||'')}</div></div>`).join('')||'<div class="v93-empty">Sem histórico ainda.</div>'}</div>`}
function bindLigacoes(){const el=$('#ligacoes'); if(!el||el._v93Bound)return; el._v93Bound=true; el.addEventListener('click',e=>{const act=e.target.closest('[data-v93-call-action]'); if(!act)return; const leads=getLeads(); const id=act.dataset.id; const lead= id? leads.find(l=>l.id===id): leads.filter(l=>l.pipeline!=='Fechado'&&l.pipeline!=='Perdido').sort((a,b)=>scoreLead(b)-scoreLead(a))[0]; if(!lead){notify('Nenhum lead disponível.');return;} if(act.dataset.v93CallAction==='open'||act.dataset.v93CallAction==='start') openCallFocus(lead.id); if(act.dataset.v93CallAction==='noanswer') {registerCall(lead.id,'Não atendeu',{autoNext:true});} if(act.dataset.v93CallAction==='whats'){navigator.clipboard?.writeText(fill(choosePB(lead).script?.whatsapp,lead)); notify('Mensagem copiada.')}}); el.addEventListener('click',e=>{const card=e.target.closest('[data-v93-lead]'); if(card&&!e.target.closest('button')){const l=getLeads().find(x=>x.id===card.dataset.v93Lead); const side=$('#v93CallSide'); if(l&&side)side.innerHTML=leadSide(l)}})}
let callTimer=null, callStart=0, callLeadId=null;
function openCallFocus(id){const lead=getLeads().find(l=>l.id===id); if(!lead)return; callLeadId=id; callStart=Date.now(); clearInterval(callTimer); const pb=choosePB(lead); const f=$('#v93CallFocus')||D.body.appendChild(Object.assign(D.createElement('div'),{id:'v93CallFocus',className:'v93-call-focus'})); f.innerHTML=`<div class="v93-call-grid"><div class="v93-panel"><div class="v93-toolbar"><button class="v93-btn soft" data-v93-focus="close">← Voltar</button></div>${leadSide(lead)}</div><div class="v93-panel"><h2>Script guiado</h2><p class="v93-muted">O roteiro aparece automaticamente e troca os campos do lead sozinho. Use como guia, não como texto para decorar.</p>${['abertura','diagnostico','valor','fechamento','whatsapp'].map((k,i)=>`<div class="v93-script-step ${i===0?'active':''}" data-v93-script-step="${k}"><div class="v93-badges"><span class="v93-badge">${esc(k)}</span></div><textarea class="v93-script-text" data-v93-script-text="${k}">${esc(fill(pb.script?.[k],lead))}</textarea><div class="v93-actions" style="margin-top:8px"><button class="v93-btn soft" data-v93-focus="copy" data-step="${k}">Copiar trecho</button><button class="v93-btn soft" data-v93-focus="savepb" data-step="${k}">Salvar no Playbook</button></div></div>`).join('')}<button class="v93-btn soft" data-v93-focus="toggleObj">Ver objeções</button><div class="v93-obj" id="v93ObjBlock">${(pb.objecoes||[]).map(o=>`<div class="v93-event"><b>${esc(o.nome)}</b><div>${esc(o.resposta)}</div></div>`).join('')}</div></div><div class="v93-panel"><h2>Execução</h2><div class="v93-kpi"><span>Duração</span><strong id="v93CallTimer">00:00</strong></div><div class="v93-field"><label>Anotação rápida</label><textarea id="v93CallNote" placeholder="Resumo da conversa..."></textarea></div><div class="v93-actions"><button class="v93-btn primary" data-v93-focus="phone">Ligar agora</button><button class="v93-btn soft" data-v93-focus="noanswer">Não atendeu e próximo</button><button class="v93-btn soft" data-v93-focus="answered">Atendeu</button><button class="v93-btn soft" data-v93-focus="return">Pediu retorno</button><button class="v93-btn dark" data-v93-focus="interested">Interessado</button></div></div></div>`; f.classList.add('active'); bindFocusOnce(f); callTimer=setInterval(()=>{const s=Math.floor((Date.now()-callStart)/1000); const m=String(Math.floor(s/60)).padStart(2,'0'); const ss=String(s%60).padStart(2,'0'); const t=$('#v93CallTimer'); if(t)t.textContent=m+':'+ss},1000)}
function bindFocusOnce(f){if(f._v93Bound)return; f._v93Bound=true; f.addEventListener('click',e=>{const b=e.target.closest('[data-v93-focus]'); if(!b)return; const a=b.dataset.v93Focus; if(a==='close'){f.classList.remove('active');clearInterval(callTimer);renderLigacoes()} if(a==='phone'){const l=getLeads().find(x=>x.id===callLeadId); if(l&&l.telefone) location.href='tel:+'+String(l.telefone).replace(/\D/g,'');} if(a==='noanswer')registerCall(callLeadId,'Não atendeu',{autoNext:true}); if(a==='answered')registerCall(callLeadId,'Atendeu'); if(a==='return')registerCall(callLeadId,'Pediu retorno'); if(a==='interested')registerCall(callLeadId,'Interessado'); if(a==='copy'){const tx=$(`[data-v93-script-text="${b.dataset.step}"]`,f); navigator.clipboard?.writeText(tx?.value||''); notify('Trecho copiado.')} if(a==='savepb'){const l=getLeads().find(x=>x.id===callLeadId); const p=choosePB(l||{}); const tx=$(`[data-v93-script-text="${b.dataset.step}"]`,f); if(p&&tx){p.script=p.script||{}; p.script[b.dataset.step]=tx.value; const ps=getPlaybooks().map(x=>x.id===p.id?p:x); savePlaybooks(ps); notify('Trecho salvo no Playbook.')}} if(a==='toggleObj')$('#v93ObjBlock')?.classList.toggle('open');});}
function registerCall(id,result,opts={}){const arr=getLeads(); const l=arr.find(x=>x.id===id); if(!l)return; const note=$('#v93CallNote')?.value||''; l.contatos=Number(l.contatos||0)+1; l.ligacoes=Number(l.ligacoes||0)+1; l.ultimoResultado=result; l.historico=l.historico||[]; l.historico.push({tipo:'Ligação',resultado:result,data:today(),hora:new Date().toTimeString().slice(0,5),obs:note}); if(result==='Não atendeu'){l.followup='Sem resposta';l.proximaData=tomorrow();l.proximaHora='10:00'} if(result==='Pediu retorno'){l.followup='Retorno marcado';l.proximaData=tomorrow();l.proximaHora='15:00'} if(result==='Atendeu'){l.followup='Engajado';l.pipeline=l.pipeline==='Lead'?'Contato':l.pipeline;l.proximaData=tomorrow()} if(result==='Interessado'){l.followup='Proposta enviada';l.pipeline='Proposta';l.proximaData=tomorrow()} saveLeads(arr); notify('Contato registrado: '+result); if(opts.autoNext){const next=arr.filter(x=>x.id!==id&&x.pipeline!=='Fechado'&&x.pipeline!=='Perdido').sort((a,b)=>scoreLead(b)-scoreLead(a))[0]; if(next) openCallFocus(next.id); else {$('#v93CallFocus')?.classList.remove('active'); renderLigacoes();}} else {renderLigacoes();}}
function renderPlaybooks(){const el=$('#playbooks'); if(!el)return; const ps=getPlaybooks(); const leads=getLeads(); el.innerHTML=`<div class="v93-shell">${renderTop('Playbooks comerciais','Estratégia, scripts e cadências para orientar Ligações e Follow-ups sem duplicar páginas antigas.',`<button class="v93-btn ghost" data-v93-pb-action="new">Criar playbook</button><button class="v93-btn ghost" data-v93-pb-action="export">Exportar</button>`)}${renderKpis([{label:'Playbooks',value:ps.length},{label:'Scripts',value:ps.reduce((s,p)=>s+Object.keys(p.script||{}).length,0)},{label:'Cadências',value:ps.reduce((s,p)=>s+(p.cadencia||[]).length,0)},{label:'Leads',value:leads.length}])}<div class="v93-tabs"><button class="v93-tab active" data-v93-pb-tab="estrategia">Estratégia</button><button class="v93-tab" data-v93-pb-tab="scripts">Scripts</button><button class="v93-tab" data-v93-pb-tab="cadencias">Cadências</button></div><div id="v93PbBody"></div></div>`; bindPlaybooks(); renderPbTab('estrategia');}
function renderPbTab(tab){const body=$('#v93PbBody'); if(!body)return; $$('.v93-tab[data-v93-pb-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v93PbTab===tab)); const ps=getPlaybooks(); if(tab==='estrategia')body.innerHTML=`<div class="v93-grid"><div class="v93-panel"><h2>Biblioteca</h2><div class="v93-card-list">${ps.map(p=>`<div class="v93-card"><div><b>${esc(p.nome)}</b><div class="v93-muted">${esc(p.canal)} · ${esc(p.segmento)} · ${esc(p.etapa)}</div></div><button class="v93-btn soft" data-v93-pb-action="edit" data-id="${esc(p.id)}">Editar</button></div>`).join('')}</div></div><div class="v93-panel"><h2>Aplicar em lead</h2><div class="v93-field"><label>Lead</label><select id="v93PbLead">${getLeads().map(l=>`<option value="${esc(l.id)}">${esc(l.empresa||l.nome)}</option>`).join('')}</select></div><button class="v93-btn primary" data-v93-pb-action="preview">Gerar texto personalizado</button><div id="v93PbPreview" class="v93-empty" style="margin-top:12px">Escolha um lead.</div></div></div>`; if(tab==='scripts')body.innerHTML=`<div class="v93-panel"><h2>Scripts por canal</h2>${ps.map(p=>`<div class="v93-card"><div><b>${esc(p.nome)}</b><div class="v93-muted">Abertura: ${esc((p.script?.abertura||'').slice(0,140))}</div></div></div>`).join('')}</div>`; if(tab==='cadencias')body.innerHTML=`<div class="v93-panel"><h2>Cadências</h2>${ps.map(p=>`<div class="v93-card"><div><b>${esc(p.nome)}</b><div class="v93-badges">${(p.cadencia||[]).map(c=>`<span class="v93-badge">${esc(c)}</span>`).join('')}</div></div></div>`).join('')}</div>`}
function bindPlaybooks(){const el=$('#playbooks'); if(!el||el._v93Bound)return; el._v93Bound=true; el.addEventListener('click',e=>{const tab=e.target.closest('[data-v93-pb-tab]'); if(tab){renderPbTab(tab.dataset.v93PbTab);return;} const act=e.target.closest('[data-v93-pb-action]'); if(!act)return; if(act.dataset.v93PbAction==='new'){const ps=getPlaybooks();ps.push({id:uid('pb'),nome:'Novo playbook',segmento:'Geral',etapa:'Primeiro contato',canal:'Ligação',script:{abertura:'Oi, {nome_lead}. Posso te explicar rapidamente o motivo do contato?',diagnostico:'Como vocês acompanham os contatos hoje?',valor:'A ideia é organizar melhor os retornos.',fechamento:'Faz sentido uma reunião rápida?'},objecoes:[],cadencia:['Dia 0 — Ligação']});savePlaybooks(ps);renderPlaybooks();} if(act.dataset.v93PbAction==='preview'){const l=getLeads().find(x=>x.id===$('#v93PbLead')?.value);const p=choosePB(l||{});const prev=$('#v93PbPreview');if(prev&&l)prev.innerHTML=`<b>${esc(p.nome)}</b><p>${esc(fill(p.script.abertura,l))}</p><p>${esc(fill(p.script.diagnostico,l))}</p><button class="v93-btn soft" data-v93-pb-action="copyPrev">Copiar</button>`;} if(act.dataset.v93PbAction==='export'){const blob=new Blob([JSON.stringify(getPlaybooks(),null,2)],{type:'application/json'});const a=D.createElement('a');a.href=URL.createObjectURL(blob);a.download='playbooks-crm-v93.json';a.click();}})}
function renderMetricas(){const el=$('#metricas'); if(!el)return; const leads=getLeads(); const s=kpis(leads); el.innerHTML=`<div class="v93-shell">${renderTop('Métricas','Métricas, Dashboard e Perdas consolidados em uma única aba organizada.',`<button class="v93-btn ghost" data-v93-met-tab="dashboard">Dashboard executivo</button><button class="v93-btn ghost" data-v93-met-tab="perdas">Perdas</button>`)}${renderKpis([{label:'Leads',value:s.total},{label:'Pipeline',value:'R$ '+s.valor.toLocaleString('pt-BR')},{label:'Propostas',value:s.propostas},{label:'Perdidos',value:s.perdidos}])}<div class="v93-tabs"><button class="v93-tab active" data-v93-met-tab="geral">Visão geral</button><button class="v93-tab" data-v93-met-tab="dashboard">Dashboard executivo</button><button class="v93-tab" data-v93-met-tab="perdas">Perdas</button><button class="v93-tab" data-v93-met-tab="campanhas">Campanhas</button><button class="v93-tab" data-v93-met-tab="atividades">Atividades</button></div><div id="v93MetBody"></div></div>`; bindMetricas(); renderMetricasTab('geral');}
function renderMetricasTab(tab){const b=$('#v93MetBody'); if(!b)return; $$('.v93-tab[data-v93-met-tab]').forEach(x=>x.classList.toggle('active',x.dataset.v93MetTab===tab)); const leads=getLeads(); if(tab==='geral')b.innerHTML=`<div class="v93-grid"><div class="v93-panel"><h2>Pipeline por etapa</h2>${PIPE_STAGES.map(st=>`<div class="v93-card"><div><b>${st}</b><div class="v93-muted">${leads.filter(l=>l.pipeline===st).length} leads</div></div><span class="v93-badge">R$ ${leads.filter(l=>l.pipeline===st).reduce((s,l)=>s+Number(l.valor||0),0).toLocaleString('pt-BR')}</span></div>`).join('')}</div><div class="v93-panel"><h2>Ações pendentes</h2>${leads.filter(l=>l.proximaData&&l.proximaData<=today()).map(l=>leadCard(l)).join('')||'<div class="v93-empty">Nenhuma ação vencida.</div>'}</div></div>`; if(tab==='dashboard')b.innerHTML=`<div class="v93-panel"><h2>Dashboard executivo</h2><p class="v93-muted">Resumo para reunião comercial: pipeline, conversões, propostas e próximos riscos.</p>${renderKpis([{label:'Valor total',value:'R$ '+getLeads().reduce((s,l)=>s+Number(l.valor||0),0).toLocaleString('pt-BR')},{label:'Contato hoje',value:getLeads().filter(l=>l.proximaData===today()).length},{label:'Fechados',value:getLeads().filter(l=>l.pipeline==='Fechado').length},{label:'Riscos',value:getLeads().filter(l=>l.followup==='Sem resposta').length}])}</div>`; if(tab==='perdas')b.innerHTML=`<div class="v93-panel"><h2>Perdas</h2>${leads.filter(l=>l.pipeline==='Perdido').map(l=>leadCard(l)).join('')||'<div class="v93-empty">Nenhuma perda registrada.</div>'}</div>`; if(tab==='campanhas')b.innerHTML=`<div class="v93-panel"><h2>Origem e campanhas</h2>${Object.entries(leads.reduce((g,l)=>{g[l.campanha||l.origem||'Sem origem']=(g[l.campanha||l.origem||'Sem origem']||0)+1;return g},{})).map(([k,v])=>`<div class="v93-card"><b>${esc(k)}</b><span class="v93-badge">${v} leads</span></div>`).join('')}</div>`; if(tab==='atividades')b.innerHTML=`<div class="v93-panel"><h2>Atividades</h2>${leads.flatMap(l=>(l.historico||[]).map(h=>({l,h}))).slice(-20).reverse().map(x=>`<div class="v93-event"><b>${esc(x.l.empresa)} — ${esc(x.h.tipo)}</b><div>${esc(x.h.resultado)} · ${esc(x.h.data)} ${esc(x.h.hora||'')}</div></div>`).join('')||'<div class="v93-empty">Sem atividades.</div>'}</div>`}
function bindMetricas(){const el=$('#metricas'); if(!el||el._v93Bound)return; el._v93Bound=true; el.addEventListener('click',e=>{const t=e.target.closest('[data-v93-met-tab]'); if(t)renderMetricasTab(t.dataset.v93MetTab)})}
function renderPipelineSafe(){try{if(window.CRMV94Official&&typeof window.CRMV94Official.renderPipeline==='function')window.CRMV94Official.renderPipeline();else if(typeof window.renderBoard==='function')window.renderBoard();}catch(e){console.warn('Pipeline oficial falhou; fallback V93',e); const el=$('#pipeline'); if(el){const leads=getLeads();el.innerHTML=`<div class="v93-shell">${renderTop('Pipeline','Kanban, tabela e funil real conectados ao lead único.','')}<div class="v93-kanban">${PIPE_STAGES.map(st=>`<div class="v93-col"><h3>${st}<span>${leads.filter(l=>l.pipeline===st).length}</span></h3>${leads.filter(l=>l.pipeline===st).map(l=>leadCard(l)).join('')||'<div class="v93-empty">Sem cards</div>'}</div>`).join('')}</div></div>`;}}
}
function renderFollowup(){try{if(window.CRMV92FollowupActive&&typeof window.CRMV92FollowupActive.render==='function')window.CRMV92FollowupActive.render();else if(window.CRMV92FollowupActive&&typeof window.CRMV92FollowupActive.init==='function')window.CRMV92FollowupActive.init();}catch(e){console.warn('Follow-up V92 falhou',e)} }
function preloadV93Modules(){
  // Preenche os módulos V93 uma vez no carregamento para evitar que o usuário veja
  // o placeholder "Carregando módulo" se a navegação antiga não disparar o render.
  try{ renderGarimpo(); }catch(e){ console.warn('Pré-render Garimpo V93 falhou', e); }
  try{ renderLigacoes(); }catch(e){ console.warn('Pré-render Ligações V93 falhou', e); }
  // Playbooks e Métricas agora são pré-renderizados pelo motor V94, evitando o bloco antigo no topo.
  try{ renderFollowup(); }catch(e){ console.warn('Pré-render Follow-up V92/V93 falhou', e); }
}
function protectLoadingState(){
  // Se alguma aba V93 estiver ativa e ainda estiver presa no texto de carregamento,
  // renderiza de novo o motor oficial da própria aba.
  ['garimpo','ligacoes','playbooks','metricas','cadencias'].forEach(id=>{
    const el=$('#'+id);
    const txt=(el?.textContent||'').trim();
    if(el && el.classList.contains('active') && (/Carregando módulo V93/i.test(txt) || (id==='cadencias' && !txt))){
      route(id);
    }
  });
}
function boot(){
  // remove visible nav entries for dashboard/perdas and route old buttons to metricas
  $$('[data-view="dashboard"],[data-view="perdas"]').forEach(n=>{const cls=(n.className||'').toString(); if(/nav-item|rail-btn|tab/.test(cls)) n.remove(); else n.setAttribute('data-view','metricas');});
  ['garimpo','ligacoes','playbooks','metricas'].forEach(id=>{const el=$('#'+id); if(el)el.className='view grid-view v93-view v93-'+id+'-view'+(el.classList.contains('active')?' active':'');});
  const follow=$('#cadencias');
  if(follow){follow.classList.remove('v82-followups-section','v91-followup-section');follow.classList.add('v92-followup-view');}
  preloadV93Modules();
  const hash=(location.hash||'').replace('#','');
  const current=hash||$('.view.active')?.id||localStorage.getItem('crm_current_view')||localStorage.getItem('currentView')||localStorage.getItem('activeView')||'inicio';
  if(['garimpo','ligacoes','cadencias'].includes(current)) route(current);
  setTimeout(protectLoadingState,120);
  setTimeout(protectLoadingState,600);
}
window.CRMV93Official={route,renderGarimpo,renderLigacoes,renderPlaybooks,renderMetricas,renderFollowup,renderPipelineSafe};
const oldSet=window.setView;
window.setView=function(view){ if(['garimpo','ligacoes','cadencias'].includes(String(view))){route(String(view));return;} if(typeof oldSet==='function')return oldSet.apply(this,arguments); setOnlyView(String(view)); };
try{setView=window.setView}catch(e){}
bindNav();
if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
